### ISSUE TITLE
Crash in beta

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1001]
http://pastebin.com/DNYwRU5G

**Comment by Crotalus** [comment]
Link to replay: http://replay.faforever.com/4034885

Watched replay, it ends right after crash, I guess all players crashed at the same time then?

**Comment by Crotalus** [comment]
Hmm very interesting, you send CMDST_Terminate @ tick 5248 when you're gone / crash / disconnect, after that we get some commands for other players until tick 5263.

The weird thing is that we don't have any CMDST_Verify around tick 5250 which should be expected (it verifies every 50 ticks).

No idea what's that about... maybe GPG insert those replay commands with some tick delay due to networking and that's why the last verify round didn't show up,  I have no idea.

**Comment by Crotalus** [comment]
I guess that "delayed verify hash stuff" could fail at network disconnect somehow which then makes the game run fine while the inserting of verify in replay could be wrong, thus ending up with a desynced replay?

**Comment by aeoncleanse** [comment]
It was a game with my friends. They continued playing. The sim crashed, but resumed for them once I terminated forgedalliance.exe

**Comment by Crotalus** [comment]
Oh, they continued playing? Hmm that's interesting... would mean replay vault saves a shortened / failed version then instead of the "best" (longest or whatever) one.

Maybe one of them still have a more complete replay in C:\ProgramData\FAForever\replays, would be very nice if it could be attached to this issue

**Comment by aeoncleanse** [comment]
If the replay is stored there automatically, I'm certain I can get all 6

**Comment by Crotalus** [comment]
With this being a user-side crash, let's hope this crash was due to the glorious "Crash when you press stop without having units selected" bug.

Closing this for now (keep eyes open for crashes in current `release/3652`)
