### ISSUE TITLE
Error in normal game

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1032]
Blodir gets this when he's trying to host.

warning: Error running OnFrame script in CScriptObject at 1105f1c0: ...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua(78): attempt to perform arithmetic on upval `speed' (a nil value)
         stack traceback:
                ...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua(78): in function <...ramdata\faforever\gamedata\lua.nx2\lua\maui\text.lua:75>

Did we fix this already?

**Comment by duk3luk3** [comment]
Pretty sure we fixed that. It's related to scrolling text in the lobby. The [StreamText](https://github.com/FAForever/fa/blob/develop/lua/maui/text.lua#L70) constructor should raise an error if no valid speed is passed to it (so we don't get useless stacktraces that don't say where the error actually comes from), or use a default speed of 20 since everyone uses 20 anyway.

Somebody must have clobbered my fix from PR #880.

**Comment by aeoncleanse** [comment]
Well this was reported in the non-beta, so I guess it's probably fixed then. Thanks! :)
