### ISSUE TITLE
unit (T3 arty) not fring

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1093]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11183

might be link to https://github.com/FAForever/fa/issues/1089

**Comment by duk3luk3** [comment]
Seems the unit is stuck in a loop between states.

Unfortunately, the unit has no special code at all and is not even modified in any way from how it was in GPG, so this is probably an engine glitch that we can't do anything about.

**Comment by duk3luk3** [comment]
You can see the unit rapidly changing states and even hear the sound effects associated with each state so it should be very possible to find out which states it's oscillating between and maybe the unit's weapon stats could be tweaked to make the problem disappear. But this is way out of my area of knowledge.

**Comment by Crotalus** [comment]
Seems like Cybran Heavy Artillery (URL0304) has invalid blueprint values for its weapon/projectile, it cannot calculate a ballistic solution due to MuzzleVelocity being too low (22) for that distance / height whatever.

It's easy to test on Setons, spawn it at the southern airspot and ground fire behind the mountains in the back (max range distance). It will just stand looping, increasing the muzzle velocity to 23-24 seems to solve it though.

**Comment by duk3luk3** [comment]
What do we want GuardScanRadius to be for this unit? It is also 30 for the Seraphim T3 Mobile Arty where the blueprint is in faf.

**Comment by Crotalus** [comment]
I suggest removing AI.GuardScanRadius so it defaults to their max weapon range instead. If you add in the blueprint, do the muzzle velocity change as well to prevent the cycle loop mentioned above.

**Comment by duk3luk3** [comment]
OK!

**Comment by aeoncleanse** [comment]
Need to increase MuzzleVelocity so it can fire, and look at removing GSR from the unit.
