### ISSUE TITLE
strat bomber killing eachother

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1099]
not sure if it has been fix or not.
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10327

**Comment by speed2CZ** [comment]
This is question of balance. Bomb has a spash damage and strats themselves are not imune to that. So if the bomb explodes close enough to starts it can kill them. I call @Zockyzock

**Comment by Zockyzock** [comment]
zlo said everything of matter in the thread

**Comment by Exotic-Retard** [comment]
could i just quickly but in here to say: fixed in equilibrium 2015
also some other observations: 
-t1 bombers have the same issue, which i experienced in spectacular fashion during a game where 20 bombers died to their own bombs
-any unit is immune to its own weapon
-this usually happens due to shield + aoe, but can also happen due to steep cliffs and a high lift factor
-its possible to code advanced things that turn off the damage for the strats only if they are in air and only from allies
-its also possible to disable collisions with air units for a short time so bombs fall through other planes
-making strats fly higher/lower will mess with a bunch of things: targetting ; asf ; bomb-dropping ; flak (not in eq)
-easiest solution is to turn off friendly fire

**Comment by shalkya** [comment]
decision has been made to make strats immune to the other owner strats. fixed in #2570
