### ISSUE TITLE
can't assist scu drone

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1102]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9916

tested on faf beta. it still doesn't work.

**Comment by shalkya** [comment]
nothing can assist it (from hives to engie, scu and acu)

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse @Crotalus  isn't this a regression issue?

**Comment by aeoncleanse** [comment]
No clue. Someone check normal game. If not, 3653.

**Comment by Crotalus** [comment]
Seems to be non-regression, something with drones being air units. A engineer / acu which are able to build something the drone is building can actually assist it. 

Otherwise not, also SCU never starts assisting it (probably due to that buggy REBUILDER behavior).

Tried to mess around with the drone blueprints to find out if it's possible to change the behavior but so far the only thing that works is if Physics.MotionType is changed from RULEUMT_Air.

So the solution is maybe to alert the drones guarding units when they start building/assisting something (CheckAssistFocus). Wouldn't cover the case when you order assist on an already working drone though.

Also, players can bypass the behavior by doing an assisting ground order also until this is fixed.

**Comment by shalkya** [comment]
ok i've an uptade on this one !
it's my fault i wasn't careful at my first test, all unit can assist sacu drone, but for some reason they can only build thing that are at their tech level.
eg, T2 engie or kenel can assist sacu drone when sacu drone are building T1/T2 stuff.
hope it help in fixing the bug

https://gist.github.com/shalkya/3c7fde34815e8356177c929e74f9dd22

**Comment by MrRowey** [comment]
@Garanas jsut tested this.

if the SACU initiations the build and the drone auto starts to assist the build but if you have any engine assisting that drone it will not assist the build unless the drone is specifically told that it is building the structure

Way I testes is get range of encies assisnt the drone of the SACU then get the SACU to build a nuke all the engies assisng will not assist the construction.

**Comment by Garanas** [comment]
Doesn't appear to be something we can / should fix. Just don't assist flying engineer drones.

**Comment by MrRowey** [comment]
Yeh it a verry niche case so dont think that it somthing that need to be fixed so could be closed @Garanas ?
