### ISSUE TITLE
Code Cleansing

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1183]
Go through all LUA code files and clean them up:
- replace "##" with "--"
- replace "!=" with "~="
- replace tabs with spaces
- remove multiple blank lines with single blank line
- fix typos in comments
- fix indent of source code 
- did I miss something?

Best time to do these changes, is just after 3652 patch

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ please add labels: 3653, nice to have, code style,

**Comment by aeoncleanse** [comment]
We operate a policy of 'Fix it when you use it' to avoid polluting the blame and history.

**Comment by Sheeo** [comment]
Indeed, I did not actually read the issue when adding labels.

We want to avoid want huge commits that only do this.

**Comment by yousless** [comment]
Hi,
Since I don't know about lua programming maybe I can help you with this. I have some questions though..

Looking at the files I noticed that some times ## were used like this:
##################################################
# Comment
##################################################
Should I replace them with hyphens here also.

How many spaces should I replace a tab with?

I will look on how to spell check comments later..

For indenting I am not sure how good emacs lua-mode is..

**Comment by aeoncleanse** [comment]
If you're affecting that file, yes. I try personally to remove comment walls wherever not totally necessary, and shrink them everywhere else. I also make sure to have -- Comment, with both the space and the capital letter, but I'm just pedantic :)

**Comment by HUSSAR-mtrela** [comment]
closing this issue since we agreed that clean up should happen on a file basis or when needed.
