### ISSUE TITLE
Ravager Adjacency

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1185]
When reloading Ravager uses -50E/s but if you add T1 pgen next to it it raises to -55E/s and then with more pgen the value is decreasing but from -55
0 pgens -50
1 pgen  -55
2 pgens -54 etc

Some other random data: 1 T3 pgen -51E/s, 1 T2 Pgen -52 
so right now no adjacency best adjacency :D

**Comment by aeoncleanse** [comment]
Didn't realise this even had adjacency lol. Or a power drain for that matter :p

**Comment by speed2CZ** [comment]
It uses power when reloading, excatly 50E. Maybe it could use some balance touch @Zockyzock considered that T2 arty needs 1000E to reload

**Comment by Crotalus** [comment]
Should be the same issue as with rapid arty etc, it shows higher energy draw due to adjacency bonus reducing total energy needed but keeping drain / s the same, so in reality it draws for 0.98s or something but UI see current energy usage and multiply by 10 to get a per second value.

**Comment by Exotic-Retard** [comment]
i dunno what the purpose of this was exactly but it still shows it wrong!
![](https://i.imgur.com/A5nAGN0.jpg)
here it should be 45 for 10% adjacency and shows up as 48 instead.

also i realised that the fix for this causes loads of other insane complications for t3 arty and stuff, where they drain less energy as well as draining for shorter periods of time. not sure if that was intended, but it certainly isnt exactly intuitive.

**Comment by speed2CZ** [comment]
Fixed already
