### ISSUE TITLE
sera stop firing torpedo for sometime

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1259]
After an attack order, if you give an other order, it will stop shootibg torpedo for 2 sec.
The solution is too reduce checkscanradius (something like that) from 2s to 0.2s.

I will post replay (log if neccessary) later

**Comment by shalkya** [comment]
https://faforever.slack.com/files/keyser/F17UQK55E/4740815-keyser.fafreplay

**Comment by Exotic-Retard** [comment]
xDDD
its TargetCheckInterval  not checkscanradius. i would like it if my instructions are not twisted like that in the future. this can be solved by writing it down <3

in any case fixed in equilibrium xD
might want to look through other units for similar behaviour. (set it to ~10% of the reload time)
this is reproducible when you have an attack order given and give a mover order; the unit in question gets this timer reset and so only checks for a target after this interval.
