### ISSUE TITLE
Rocks and wrecks don't die to ACU explosion

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1265]
when I killed the first guy at min 8+- rocks around him did not die to

content.faforever.com/faf/vault/replay_vault/replay.php?id=4748337

at min 13:30 T1 wrecks around ACU dont die

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/blob/develop/lua/sim/DamageArea.lua#L21

Reclaimables are specifically hit with damage, so not sure what's going on.

**Comment by duk3luk3** [comment]
`GetReclaimablesInRect` in [Unit.lua](https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L2124) passes a `Rect` to the function instead of the coordinates. But [just a couple lines under that](https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L2152) it passes the coordinates.

Does the function support both or is this fucky?

**Comment by aeoncleanse** [comment]
Well, testing in SB shows it blowing up all the wrecks and reclaim, so I'd say it works... Except for @speed2CZ apparently...
