### ISSUE TITLE
  Salem's 'walk on land' button

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1328]
http://forums.faforever.com/viewtopic.php?f=42&p=127646#p127646

**Comment by Uveso** [comment]
i was trying it, but i failed.

Salem has the MotionType AmphibiousFloating. So the SupCom.exe is in control for the movements and restrictions.
Waiting for an layer change event is to late for any action, because the layer is already changed then.

To prevent the Salem to enter Land i tried to change the motiontypes Physics.MotionType = 'RULEUMT_AmphibiousFloating' and AltMotionType = 'RULEUMT_Water'

This works, but this is stored inside the blueprint and i cant change blueprints after the unit is build.

I tried this of course, but changing the blueprint don't has a affect to an already build unit.
I guess the motion type is stored inside the c-object of the unit.

Well, i dont see a way to do this.

**Comment by Crotalus** [comment]
A really ugly solution would be to respawn the unit without AltMotionType set if you click on the "no land walking" button. The downsides to this are massive though, units would lose targeting of it etc :)

**Comment by JJ173** [comment]
Probably a dead issue (2 years later almost). As it's still open, let me have a fiddle with this and see if I can produce any other ugly or smooth solutions for this. Since it's not a bug, it'll remain on low priority, but I'll give it a go at some point.

**Comment by Uveso** [comment]
The problem is still, that the layerchange event is triggered from the c-engine.
If you get the event, then the salem is already on land.

You have to move it back to water.

Thats all possible but i can't manage the AI behavior in this situation.
You have to disband the single unit from the attackplatton, then move it back to water.
Now you have the problem, if you add the unit back to the attackplatoon it will move on land instantly.
And you can't just let the unit where it is, because the AI will not move it if it has no platoon.

Please don't make a player only solution and have the AI stuck in this situation!
