### ISSUE TITLE
Submerge/Surface button

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1333]
http://forums.faforever.com/viewtopic.php?f=42&t=12523&p=127771#p127771

labels : 
nice to have
ui (?)
enhancement
low

**Comment by Uveso** [comment]
Well, pressing the dive button sends this:
`
IssueCommand(GetUnitCommandFromCommandCap(RULEUCC_Dive))
`
This command is send to all selected units.
But thisis a toggle command. You cant tell all units to dive or surfacing, only to toogle their actual state.
(You cant change this like the shields in #1262 )

maybe possible to deselect all units who are already dived, issue a command to all others to dive, and the reselect all units.

But deselect units and reselecting them is more a hack then a good solution.
Maybe someone else has a better idea.

**Comment by Crotalus** [comment]
IssueUnitCommand takes a list of units instead of selection so maybe that would work? Otherwise we could invent a new simcallback which takes care of the dive / surface logic depending on unit state.

Another problem with the dive button is the apparent "lag" before the unit change state from surfaced / submerged which is extra problematic with the toggling

**Comment by Uveso** [comment]
Crotalus! Thanks again!

IssueUnitCommand did the trick !

now it was easy.
