### ISSUE TITLE
UEF gunships can't be given attack order when landed on water

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1392]
As the title says, uef gunships that are landed on water can't be given an order to attack units, you have to give a move order so they take off then give the attack order.

**Comment by Uveso** [comment]
After testing i know, you mean the Tech2 Gunship "Stinger", not the Tech2 Gunship.

This is easy to explain. Gunships can't land on water :)

The stinger is not only a gunship, its also a transporter!

The Transporter ability makes the Stinger land on water.
But he can't attack from water, because all weapons need the layer Air to aim and fire. But while landed, the Layer is Water. And the stinger dont has weapons, that can fire while in water :)

You can test this by building any transporter. While in air, the transporter can aim at enemies. But if landed it cant aim. like the Stinger.

**Comment by Uveso** [comment]
I made a fix, ready for testing: #1393

**Comment by Uveso** [comment]
hehe, no problem. It was not meant as a reproach :)

**Comment by Uveso** [comment]
Merged into develop, i guess this can be closed.

**Comment by Exotic-Retard** [comment]
somewhat skirting round the topic - how would one go about making non transporting gunships land on water?
or perhaps the opposite - making transports not land on water, is that possible?

**Comment by aeoncleanse** [comment]
In short: No. Landing on water seems tied to the Transport category.
