### ISSUE TITLE
Warning in log "Game object has been destroyed"

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1408]
I don't think it's breaking anything, it can be seen during cinematic intro in first FA mission (Black Day). When dead gunships are falling onto a shield I believe?

```
WARNING: Error running lua script: ...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(225): Game object has been destroyed
         stack traceback:
            [C]: in function `GetArmy'
            ...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(225): in function <...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua:224>
```

Responsible line of code https://github.com/FAForever/fa/blob/develop/lua/shield.lua#L225

**Comment by Uveso** [comment]
This always happen, when a unit is destroyed to early by a self:destroy() command etc. This only means that the c-object of an unit is already deleted, but lua is still runing on the unit.

In this case the function CreateImpactEffect will fail, but it doesent matter, because it only affects a not existent unit.

**Comment by speed2CZ** [comment]
This is no longer the case
