### ISSUE TITLE
Laggy hotkeys

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1433]
Some hotkeys are laggy, namely "toggle through available fire states" and "toggle repeat build". They take a second or two to work so for example if you press the repeat build hotkey and click away from the factory too fast the hotkey command will not register. I've lost games because of factories going idle this way.
I haven't found any others that are laggy but there may be more. This lag only happens ingame with another person, sandboxing alone will not produce this lag.

**Comment by SwayGin-FAF** [comment]
This regularly happens to me with pausing factories and mexes (in sandbox as well, actually), and I'm not entirely sure whether the binary factory command hotkeys are due to lag or the command is actually being "ignored."  One possible workaround you may wish to try in the interim is pressing an on/off toggle 3 times in rapid succession if you detect a bit of a delay and suspect a command has not gone through.  I don't automatically do this myself, but if I see any kind of delay in a "pause" icon over a factory or unit, I'm learning to just do this and it's fixed.
When playing the campaign I recall having a number of problems when cycling through fire states as well, in particular with T2 artillery, and it also seemed like lag to me.  I wouldn't be surprised if they were related.

**Comment by JaggedAppliance** [comment]
#88 is related and has a possible solution.

Pressing the command multiple times quickly does not help for me.

**Comment by Uveso** [comment]
I don't see how i could optimize those functions. At least i found them :)

`Cycle through all of the available fire states` calls this function inside orders.lua:
```LUA
function CycleRetaliateStateUp()
    local currentFireState = GetFireState(currentSelection)
    if currentFireState > 3 then
        currentFireState = 0
    end
    ToggleFireState(currentSelection, currentFireState)
end
```

`Toggle factory repeat build` calls inside keymapping.lua:
```LUA
function ToggleRepeatBuild()
    local selection = GetSelectedUnits()
    if selection then
        local allFactories = true
        local currentInfiniteQueueCheckStatus = false
        for i,v in selection do
            if v:IsRepeatQueue() then
                currentInfiniteQueueCheckStatus = true
            end
            if not v:IsInCategory('FACTORY') then
                allFactories = false
            end
        end
        if allFactories then
            for i,v in selection do
                if currentInfiniteQueueCheckStatus then
                    v:ProcessInfo('SetRepeatQueue', 'false')
                else
                    v:ProcessInfo('SetRepeatQueue', 'true')
                end
            end
        end
    end
end

```

**Comment by aeoncleanse** [comment]
Clone of #88
