### ISSUE TITLE
Tanks vs Walls

### ISSUE THREAD

**Issue by Kalvirox** [FAForever/fa#150]
Forum Link
http://forums.faforever.com/forums//viewtopic.php?f=3&t=8934

**Comment by aeoncleanse** [comment]
We cannot do anything about this, I've tried everything I know and so have many others.

**Comment by Sheeo** [comment]
A way to go about it is to subdivide the wall entities with a bunch of collisionboxes that all take HP away from the wall entity. This way we increase the chances of high speed projectiles colliding with a box on its way through the wall.

But we probably don't want to make walls impenetrable, rhino vs walls is already a murderparty, and gameplay wise I think they're already more than powerful enough for what they do.

**Comment by aeoncleanse** [comment]
The problem isn't with the walls though, it's with the PD! The bug is primarily that the shot goes over the first wall (As is should), through the PD (Wut?!), and hits the wall behind. I don't know why this happens. Some have said it's because the projectile speed is fast and the hitbox is small, so it passes right through the zone in between simticks and therefore detection events, but that doesn't make sense to me, else a single PD on its own would see the same problem, and it doesn't...

**Comment by Kalvirox** [comment]
Yes, I always wondered why when you shot at t1 pd with bricks you had to kill the back wall first before you could hit the PD.. That is another bug that has been around for ages but I assumed you already knew about it. 

If/when you fix this, do check the frequency of tank shots that hit the PD afterwards and make sure it is not too much. "(As it should)" . Actually it shouldn't more often than not. I don't care if the way it was not originally designed this way but the game play element that this adds makes the t1 phase in 1v1 interesting even up to t2 stage, t1 PD with walls is still very solid.

**Comment by Sheeo** [comment]
I investigated further.

Rhinos never shoot over the first wall, from any distance. What happens is that the projectiles pass right through the wall because of their really high velocity (100). Given the size of the wall (1), in any given simtick, the Rhino projectile can pass through 10 wall sections. This confirms that the engine doesn't interpolate projectile positions in between sim ticks, to calculate collisions -- this is the real bug.

Any projectile with a velocity higher than `10` will exhibit this behavior for wall sections, and funnily enough, projectiles with extreme velocity [may pass through even larger structures](https://www.youtube.com/watch?v=fMeuv4S_BLA&feature=youtu.be).

A couple of things to take away from this:
 - High muzzle velocities should be limited
 - Rhino didn't originally have this high muzzle velocity, we should investigate what to do about it.

**Comment by aeoncleanse** [comment]
Sheeo, I tested Rhino VS a line of 10 walls, and it never made it through the 2nd for me. Do you get the same result? I suggest this means it is interpolating, but only down to 0.5, or 0.1, or something which still allows it to go through the PD.

This may be the cause of Sniperbots missing against certain targets too! I'll also add that the hitbox fixes are almost all enlargements, and should help with this issue in a general sense. For example, I bet Snipers have trouble hitting Othuum from the side right now (Teensy width on the box), and that gets fixed there.

FYI I and others have tried increasing T1 PD hitbox size in the past for the walls issue, and it doesn't work out because the walls are so close.

**Comment by Sheeo** [comment]
> Sheeo, I tested Rhino VS a line of 10 walls, and it never made it through the 2nd for me. Do you ?get the same result? I suggest this means it is interpolating, but only down to 0.5, or 0.1, or something which still allows it to go through the PD.

This will depend on where you aim it. My video proves that no interpolation is done.

> This may be the cause of Sniperbots missing against certain targets too! I'll also add that the hitbox fixes are almost all enlargements, and should help with this issue in a general sense. For example, I bet Snipers have trouble hitting Othuum from the side right now (Teensy width on the box), and that gets fixed there.

Potentially yep.

> FYI I and others have tried increasing T1 PD hitbox size in the past for the walls issue, and it doesn't work out because the walls are so close.

Increasing the size of the PD hitbox by `xyz += (0.25, 0.2, 0.25)` helped the rhino to hit it quite a bit.

**Comment by Sheeo** [comment]
Also to be noted, the problematic value for PD's is `muzzlevelocity > 50`, since the width/length of the hitbox is `0.5`

**Comment by aeoncleanse** [comment]
Then there's more to it. The ACU has the troubles too, with the blast going through the PD and hitting the rear wall, and the MV on all ACU is 35...

**Comment by Sheeo** [comment]
I'm not sure what units the MV is given in. Depending on whether it is per tick or per second we're dealing with an order of magnitude difference.
