### ISSUE TITLE
Random slots doesn't work with >8 players?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1584]
BRNKoINSANITY reported.

**Comment by Justify87** [comment]
Random slots does work with more than 8 players, but the other two (Optimal Balance, Flexible Balance) do not. Those two don't work with more than 12 players available though.

Error is thrown here:
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L1181

WARNING: Error running OnRelease script in <deleted object>: d:\github\fa\lua\ui\lobby\lobby.lua(1184): bad argument `#1` to "remove" (table expected, got nil)
         stack traceback:
         	[C]: in function "remove"
         	d:\github\fa\lua\ui\lobby\lobby.lua(1184): in function "f"
         	d:\github\fa\lua\ui\lobby\lobby.lua(1405): in function <d:\github\fa\lua\ui\lobby\lobby.lua:1265>
         	d:\github\fa\lua\ui\lobby\lobby.lua(1723): in function "LaunchGame"
         	d:\github\fa\lua\ui\lobby\lobby.lua(1756): in function <d:\github\fa\lua\ui\lobby\lobby.lua:1612>
         	d:\github\fa\lua\ui\lobby\lobby.lua(2861): in function "OnClick"
         	d:\github\fa\lua\maui\button.lua(85): in function <d:\github\fa\lua\maui\button.lua:78>
WARNING: Error running lua script: d:\github\fa\lua\ui\lobby\lobby.lua(3088): attempt to call method "pairs" (a nil value)
         stack traceback:
         	d:\github\fa\lua\ui\lobby\lobby.lua(3088): in function <d:\github\fa\lua\ui\lobby\lobby.lua:3086>

I suspect this to be the core of the problem:
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L1164

But I'm not sure, because my skills aren't good enough to get any meaning out of this code. In other words: I don't know what line 1164 to 1184 does or what the intention behind it was.

@Crotalus  explained the whole function like this:

> `autobalance_rr` lets each team pick the best player available, with team order alternating each round to even it out.

https://github.com/FAForever/fa/issues/946#issuecomment-144719338

**Comment by aeoncleanse** [comment]
Yeah, @Crotalus this needs mending to support up to 16 players please.

**Comment by aeoncleanse** [comment]
ae5b359
