### ISSUE TITLE
selen toggle sometimes reveals hidden selens, also broken

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1627]
to reproduce:
spawn selen, make it still, toggle it on.
spawn enemy aa or engy or w.e., and move it into the range of the selen from the top (not the way the selen is facing)
selen reveals itself for a second when its turning, but after that its perfectly fine.
replay: 5327333

also because ui mods it can start shooting as well (if it doesnt turn then it can do that while stealthed).

actually i dont even know why it does this, disabling the weapon doesnt help either it seems
related to how it turns to face its target though, relaxing its turning constraints and disabling SlavedToBody fixes it. apparently.

also your MaintenanceConsumption doesn't seem to work. ah well, i think its better this way anyway xD

(fixed in equilibrium of course)

**Comment by aeoncleanse** [comment]
It's working fine, I just missed a tiny thing. The cloak system is triggered by motion type becoming 'Stopped'. So if it's already still when you hit the toggle, all that does it put it into low-priority mode. It still needs to move and then stop in order to cloak up. Will look into it.

**Comment by aeoncleanse** [comment]
It becomes cloaked because the 'Decloak on spawn' code isn't working, annoyingly. It uncloaks because it's cloaked but not disabled weapon, so it turns, which counts as motion, which un-hides it. Bit of a mess.

Basically, as long as it stopped while toggled on (And therefore is properly cloaked with the E drain working) it works. Will make sure this is fixed in balance patch.
