### ISSUE TITLE
GC dealing stomp damage to shields when inside bubble

### ISSUE THREAD

**Issue by Viba** [FAForever/fa#1677]
JoonasTo and me did some sandboxing and found this:
http://recordit.co/i9pfKHthPe
For every step GC deals about 3k damage to shields.

Mainly posting this issue for record keeping, if and when fixing this might be possible sometime in the future one way or another?

**Comment by MrRowey** [comment]
This is due to the ExperimentalFootFall damage being 3500. this can be found here. so every time it put is foot down under the shield it is dealing 3.5k Dmg https://github.com/FAForever/fa/blob/deploy/fafdevelop/units/UAL0401/UAL0401_unit.bp#L190 this is something that is either Balance related to reduce this damage or to find a way of reducing the dmg dealt to shields.

**Comment by Garanas** [comment]
I'm not sure if this is someone we want to change however. It does make sense in some fashion - same principle as the Seraphim exp. bomber destroying shields when it is 'crashing' (read: flying into a commander).

**Comment by MrRowey** [comment]
@Tagada14 If this is still something that doesn't need looking into can you close please :)

**Comment by MrRowey** [comment]
Closing Issues for now Balance Team Can reopen if needed

**Comment by Tagada14** [comment]
Yeah, I don't see this as a bug or something that should be changed. Thanks for closing the issue.
