### ISSUE TITLE
selen toggle

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1705]
as it is done now, we can't make a non moving selen don't consume energy.
it will always cloack when not moving. No matter whether you toggle it on or off. toggle only use, is to not select a toggle selen into the army.
sometime you want it to be only a land scout (and not a static radar) and to not consume e. And you can't achieve that when you are not moving.

5479415

**Comment by aeoncleanse** [comment]
I know. That's how we had it before. The decision was made to _always_ have the motion-cloak enabled, and have the toggle affect only the selection priority. Take it up with Zock if you really dislike it.

**Comment by Zockyzock** [comment]
I think thats a misunderstanding. Cloak should never always be on, that's really bad. Toggle should toggle cloak + energy consumption + selection priority. Only thing that needed to change was that selens need to keep following the last order before they cloak if toggled, to have exactly the same behaviour as previous selens when on hold fire. 

If thats not possible without having them permanently drain e, it's better to remove the feature again. Selens are really buggy now, sometimes cloaked while moving/shooting..

**Comment by aeoncleanse** [comment]
No Zock, that's what I had the first time and it was _terrible_, constant complaints. And they don't permanently drain E, they drain it when cloaked (standing still). That's honestly closer to original intent than anything anyway.

We do not want to have two toggles.

**Comment by aeoncleanse** [comment]
As for the bugged stuff, there's a fix for THAT already in beta testing.

**Comment by Zockyzock** [comment]
Its not so complicated: Selen need to behave exactly as before, except instead of having to put them on hold fire, toggle with a button that is not such a "hidden feature". Then drain E when cloaked/toggled, and change selection priority. 

In the first version, selens did stop moving if you toggled and they still had a move order, which made them very annoying to use. This is all that needed to change.

Selens draining energy just by standing still is bad and can't stay.

**Comment by aeoncleanse** [comment]
Then go back to how it was originally, no E drain. It's not needed.

**Comment by Zockyzock** [comment]
No selection priority either then though. It's unfortunate, but if it's not doable..

**Comment by aeoncleanse** [comment]
? Selection priority is separate, that's the whole point. Why should no E drain == not allowing people to do selection priority, given that's a UI mod anyway?

**Comment by Zockyzock** [comment]
The e drain is the way to combat selens becoming OP with selection priority

**Comment by aeoncleanse** [comment]
Dude, it's pointless. They become strong, sure, but hardly OP, and _it's a UI mod_. People have been doing it forever. I had tonnes of complaints before that people don't want to have to remember to toggle if they want the selen to cloak up, it was annoying.

**Comment by Exotic-Retard** [comment]
if you think selen needs a nerf so much why not nerf some other stat and make the cloak a feature, as it was probably intended in the first place rather than just making it annoying to use. it not like its such a crippling nerf to have 5 e drain anyway.

atm its mostly a glorified scout with a fun and unique feature which has the potential to make it into its own unit with its own associated strategies and you are choosing to suppress that?

**Comment by shalkya** [comment]
well how would you change it ? 
having "20m 80e 80bt; -5e/s 35HP, 13dps, 16r 4sp → 30m 300e 150bt -0e/s; 75HP, 18dps, 18r, 4.5sp" for selen is not a good way. (maybe good in equilibrium since you change everything.)
Since selen got buffed (by introducing the ui mod; yes icedreamer it's a buff) when it cloack, it's logic to nerf it when it cloack. (by using -5 e for exemple).
I'm afraid that icedreamer is using his position of being able to code to influence balance decision. 
But as i said again, if you have a good idea to balance selen (since for some reason -5e + toggle can't be implemented correctly), that doesn't need complete rework, i'm eager to hear it.

**Comment by aeoncleanse** [comment]
I know it's a buff. Sure. Doesn't make it OP IMO, even without the E drain.

**Comment by aeoncleanse** [comment]
It's not that it CANT be implemented, it's that I've had so much conflicting desire about what this unit should do that I'm at the end of how many fucks I give. The most _elegant_ solution (In terms of usage) is to have it same as it's always been, with the toggle for priority of selection. E drain or no E drain I don't think makes any real difference, except E drain leads to complaints such as this one.

**Comment by Exotic-Retard** [comment]
yeah eq selen is completely different, i meant that since you just try to keep it exactly the same instead of using this as a reason to make it more interesting. (btw would like to have a discussion with you on that one)

atm that 5 e drain is a knee-jerk reaction to preserve this balance (whatever it may be), and is just annoying really. doesnt really change how its used, just slaps you a little in some cases : |
you could just change any other stat it has by like 5% to nerf it and same effect (or greater) will be achieved.
i would probably make it a little more expensive since its now better i guess. even so i think this opness is blown way out of proportion, its not like it totally makes sera n1 in ladder/teamgames right? xD

**Comment by shalkya** [comment]
well it's still giving them the possibility to have a radar+direct vision over important spot of the map for a low price, without counter until T3 air stage. (- ACU)
seems fairly good to me.

**Comment by aeoncleanse** [comment]
His point stands. Sera are not OP, nor would this alter that. Also pretty sure this ended up very close to what's in EQ Retard, though I can't properly remember.

**Comment by Exotic-Retard** [comment]
in eq we gave it more of a lab role since we think that synergies with the cloak/ambush thing more. code wise this is pretty much how i would like it atm - maximum usability, balancing by inconvenience is imho absurd.

i do agree with keyser, having vision like that is *fairly* good, but thats it. its far from making sera op. 
interestingly what he wrote sounds to me like true faction diversity which we should cherish and extend rather than try to suppress. sera is a pretty bad faction anyway, and more importantly its pretty boring xD

**Comment by aeoncleanse** [comment]
I believe with shalkya's help this 182ffa081f4f64e2306b0fee1edfd68a685e3a27 solves it.
