### ISSUE TITLE
sera/aeon nuke immune to T2 pgen death

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1708]
5482834

**Comment by duk3luk3** [comment]
could you write a bit more than just a replay id? like, when does it happen, and what exactly is the bug...

**Comment by shalkya** [comment]
can't you read the title ?
imo this bug report is more than enough for anyone to understand.

**Comment by duk3luk3** [comment]
no, this is a terrible bug report. I don't want to watch a one-hour replay or however long it is and then miss the point where the bug actually happens because you couldn't be bothered to write down a timestamp and because you couldn't be bothered to say if you're talking about the nuke launcher or the projectile or something entirely different.

**Comment by shalkya** [comment]
i guess you just didn't look at the replay. that's unfortunate :(
maybe next time watch and comment

**Comment by Exotic-Retard** [comment]
..... anyway

not delving too much into this, it looks like a hitbox thing. the uef nuke has x/y values of 2.9 while for aeon/sera its only 2, so the explosion aoe simply doesnt reach them.

either increase pgen aoe on death or increase nuke hitbox, or whatever tbh

**Comment by shalkya** [comment]
well i guess making same hitbox for all nuke seems logic
