### ISSUE TITLE
Reclaim overlay problems

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1712]
I made an addition to the ultimate maps (at least some) where the reclaim value of the rocks can be adjusted at the start of the game.

Example Canis: Most rocks have a value of 38 mass.
reduction can be 20%, 40%,...

it works properly when you select 20% and 40%: the rocks show a value of 30/23 mass and the overlay disappears when you zoom after the stone is reclaimed.

it doesnt work properly when the reduction is larger: selecting 60% or 80% will make all markers show the 38 mass from the blueprint and these markers dont vanish after reclaiming the rock and zooming.

Tests were made with the latest version of develop.

[5494202-CookieNoob.zip](https://github.com/FAForever/fa/files/629431/5494202-CookieNoob.zip)
@Crotalus @aeoncleanse

**Comment by aeoncleanse** [comment]
This isnt a fault. Overlay doesnt show stuff under 20 mass, and the nonvanishment is another issue. Have you tested with deploy/fafdevelop since last night? That has a bunch of overlay fixes, but isnt on server yet

**Comment by CookieNoob** [comment]
I tested it today with develop.

I dont mind that stuff below 20 mass doesnt show up (thats not the bug), but that stuff that has a value of below 20 mass is shown as 38 mass (and also that the overlay doesnt disappear)

**Comment by aeoncleanse** [comment]
So what happens is on map start, it's entered at full value, then it's modified but to less than the limit, so it doesn't sync. Also there's a difference between develop and deploy/develop. Make sure it's the latter.

**Comment by CookieNoob** [comment]
hm, so is it a non-issue or not? shouldnt it check that the reclaim is changed below the threshold and delete the markers?

**Comment by aeoncleanse** [comment]
Given I'm not certain what the current code state is in terms of previously known bugs, I'm not sure yet :p

**Comment by duk3luk3** [comment]
@CookieNoob sounds like your mod doesn't adjust everything correctly.

**Comment by CookieNoob** [comment]
@duk3luk3 hm the code changes the reclaim value of the rocks. That works fine... what else is required to change?

**Comment by duk3luk3** [comment]
Does it change the `MaxMassReclaim` value?

**Comment by CookieNoob** [comment]
it does this:
r:SetMaxReclaimValues( 
    percentage * (r:GetBlueprint().Economy.ReclaimTime), 
    percentage * (r:GetBlueprint().Economy.ReclaimMassMax),
    percentage * (r:GetBlueprint().Economy.ReclaimEnergyMax)
)

**Comment by duk3luk3** [comment]
When does it do that?

**Comment by CookieNoob** [comment]
in OnStart(), when the map is launched.

**Comment by duk3luk3** [comment]
Hypothesis: `SyncMassLabel` is first called before `OnStart()`, leading to lots of labels being initialized. Then every time `SyncMassLabel` is called again, now with `MaxMassReclaim` set properly, it exits early because of https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Prop.lua#L128 and the label never gets a chance to be cleaned up.

**Comment by CookieNoob** [comment]
so the solution would be to replace the elseif by else and drop this check?

**Comment by aeoncleanse** [comment]
No. The introduction of this new structure is what prevents crap like this. When one of your 38 mass label objects is killed, it _should_ be removed. Old code would keep it around.

**Comment by TheKeyBlue** [comment]
What cookienoob and duk3luk3 suggest is to simply not check if a prop should have a label or not inside Prop.lua and send everything through Sync.Reclaim. Then you only do the threshold test in reclaim.lua.

This would actually make a lot of sense. (having `minimumLabelMass` in Prop.lua isn't really nice)

**Comment by aeoncleanse** [comment]
hmm. Cool, take a look at it keyblue :)

**Comment by TheKeyBlue** [comment]
Wait. What do you mean? Take a look at it?
The only change would be to do this:

CookieNoobs comment
> so the solution would be to replace the elseif by else and drop this check?

duk3luk3's PR
> Entirely unnecessarily complex fix, could be done much easier by just changing
elseif self.MaxMassReclaim >= minimumLabelMass then to else. The extra flag is entirely a premature optimization.

So i simply support this suggestion.

**Comment by aeoncleanse** [comment]
Ok decision made: The maps are just going to have to find

**Comment by aeoncleanse** [comment]
Dammit phone.... Find a way to do it without altering maxmassreclaim, which should always be the bp value, and never change once set

**Comment by CookieNoob** [comment]
lol why that?

I think the reclaim overlay should work in a way that it correctly displays the mass in the props.
What is the problem with removing the elseif there and replacing it with a simple 'else'??

**Comment by aeoncleanse** [comment]
Because that ripples into fundamental issues with how the rest of it works, as I found when I tried it last night. It will not be hard to change the way the map code works, you just need to use a method other than the first one you thought of. Fact is it already correctly displays reclaim: the map vode fiddled something it shouldn't.

**Comment by CookieNoob** [comment]
>  fundamental issues
could you be a bit more specific?

**Comment by duk3luk3** [comment]
The issue with that fix is that that means *all* props will be put into the sync table every time. It may not be immediately obvious that this could be problematic, but it's simply not necessary to do that just so your reclaim adjustment can stay the way it is.

The bug is caused by `MaxMassReclaim` of a prop being adjusted after `SyncMassLabels` was already called, as it is done in the `OnStart` function of the map.

The solution is to not do that which is very simple. Just adjust the Health of the prop (i.e. reclaim left) instead.

**Comment by CookieNoob** [comment]
that is not true, there is another check after this
`        if data.mass and id then`
`            Sync.Reclaim[id] = data`
`        end`

I can do it differently yes ofc. Adjusting the health would have been my next approach.

**Comment by duk3luk3** [comment]
I don't think that code block does what you think it does. The mass will be set to zero by the code before it, but it will still be put into the sync table (`if data.mass` checks for `data.mass` not being `nil`), because otherwise the bug wouldn't be fixed.

So like @aeoncleanse said, it's complicated and not worth making more complicated or less efficient.

**Comment by CookieNoob** [comment]
are you saying that this code adds destroyed and reclaimed props below the threshold to the sync table?

If that is the case (and wanted behavior) I rest my case and implement it differently.

**Comment by TheKeyBlue** [comment]
I am actually interested in knowing what these fundamental issues are.
Would you mind sharing your findings? @aeoncleanse

**Comment by aeoncleanse** [comment]
Basically what duk3 said. I attempted to move the limit check UI side as suggested, but found that doing so  made reliably checking the labels a bit harder, while creating the situation where many props would be entered and deleted from the UI record keeper multiple, if not in some cases hundreds of times. The design went from elegant with one caveat affecting one map-type, to inelegance for all players, all the time. It's just not worth jumping through that many hoops when there are multiple ways to fix the map implementation.

**Comment by TheKeyBlue** [comment]
Oh ok. I didn't expect such effects.

Then i guess you are right, not to change anything.
