### ISSUE TITLE
Chat window can end up with it's "top" position value as -tv if you change resolution the wrong way

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1724]
This is dumb and stupid. It should stop.

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse what do you mean by "-tv"? Is the chat window off screen and one cannot drag it back to correct position?

**Comment by Exotic-Retard** [comment]
yeah so the values for its size can be negative which make it offscreen so if you want to move it you have to do so manually via game prefs

**Comment by HUSSAR-mtrela** [comment]
this should be fixed in window.lua file by correcting logic for placing a window when it is being created/moved. Also this issue occurs on other UI elements that use window (e.g. min-map) As matter of fact, I have a fix for this issue in my SupremeScoreBoard mod that is pending a new release so I will fix this issue when I integrate SSB into FAF.

**Comment by aeoncleanse** [comment]
Since it's small and relatively easy to test, could we have the window placement logic changes in a PR ASAP please?

**Comment by HUSSAR-mtrela** [comment]
yes, let me see if I can port the fix from my mod and I will create PR for it.

**Comment by MrRowey** [comment]
could be closed as is an old issue and never heard anyone complaining about this since

**Comment by MrRowey** [comment]
@Garanas  could be closed as is an old issue and never heard anyone complaining about this since
