### ISSUE TITLE
map that doesn't appear in replay vault

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1746]
i hope there is no issue already created (i've look a little bit)

there is map that doesn't appear in replay vault like farce in the forest. Would be great to fix it : by determining if this is an issue due to the map (map makers) or link to something else (coder wise).

I can also add that you can't watch game played on this map in live replay, you get this : http://imgur.com/zizl7HI

i don't remember what other map cause this (if anyone knows more, pls share there)

replay can be watch after people give their local replay.

edit : that error in screenshot, maybe due to the fact that this game has crossed swords, but it is already finished since some times.

**Comment by speed2CZ** [comment]
wrong repo

**Comment by CookieNoob** [comment]
https://github.com/FAForever/client/issues/420
https://github.com/FAForever/replay-server/issues/2

its a bug in the legacy scondary server that all replays on maps with a higher version than the first one do not show up.

sheeo about the fix: the funtionality should be implemented in the api instead of fixing the bug. i.e. it will be fixed maybe much later.

The picture you posted has nothing to do with this error, it happens when the live replay is not available (i.e. the game ended already and the server still shows ingame status). That should probably also be in the api repo as a separate issue.

**Comment by shalkya** [comment]
there is a map called "farce in tha forest" which appear in replay vault, so maybe someone uploaded the map in a version that does work with the vault...

**Comment by CookieNoob** [comment]
as I said: its not a map problem

the replay vault doesnt show maps that are more recent than the first uploaded version.

**Comment by CookieNoob** [comment]
https://github.com/FAForever/db/issues/47
https://github.com/FAForever/api/pull/77

are potentially fixing this

**Comment by CookieNoob** [comment]
@aeoncleanse you can close this since its the wrong repo anyway

**Comment by Brutus5000** [comment]
Should be fixed with https://github.com/FAForever/legacy-secondaryServer/pull/1
