### ISSUE TITLE
Mods that cause problems or need tags

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1751]
Here is a list of mods that cause performance issues or need tags in the blacklist.lua file

Assign UPGRADE/HARMFUL tag because author of these mods should use Common Mods Tools to access/find units rather then constantly check for units and thus cause UI lag:
- UI Mass Fab Manager FA - `EF3ADDB4-9D34-437F-B1C8-440DAF896802` by Stephen Evans (aka Goom)
- UI Idle Engineers - `b2cde810-15d0-4bfa-af66-ec2d6ecd561d` by "camelCase"

Assign INTEGRATED tag because FAF already provides that functionality:
- No Mexes - `58a524e0-8143-479a-b38f-4e4513b84cd8` by RaptorJesus

Assign BROKEN tag to:
- Experimental Wars - ce6f9860-d2d2-11e0-9572-0800200c9a66

**Comment by aeoncleanse** [comment]
What specifically is the problem with the ways those two mods find units?

**Comment by Exotic-Retard** [comment]
ui massfab manager ui needs a replacement because if there isnt one a bunch of people are gonna complain and not remotely care about any performance impacts you concern yourself about.

also ui massfabmanager didnt give me noticeable performance loss so youre gonna be hard pressed to justify that, and just blamed for breaking stuff

**Comment by HUSSAR-mtrela** [comment]
well, I looked at code of MassfabManager and it is a bit of mess and it would require a few days of work IMO. Also, its UI requires some work and I would not be able to stop myself from correcting it when improving that mod. In addition, EcoManager includes functionality of MassfabManager mod so it would be much better to work with @Crotalus on improving EcoManager such it provides configuration that allows players to use all its features or just managing mass fabs.

Unfortunately,  I'm still working on the Blueprint PR and 2 other mods for FAF so I cannot take another project at this moment. Besides, I think that there are more important issues/enhancements that we should be working on. However,  Exotic-Retard might be right about many people complaining about blacklisting MassfabManager especially since there is no replacement for that mod at this moment. So I think we should temporary commented that mod in the blacklist until we have replacement for it.

**Comment by aeoncleanse** [comment]
How much work would it be to JUST address the issue for which you've asked me to blacklist it?

**Comment by HUSSAR-mtrela** [comment]
IMO, it would take 2-3 days plus 1-2 days for testing. My estimation is based on schedule of one person with 2-3 hours of free time per day that can dedicate for improving that mod.

**Comment by aeoncleanse** [comment]
I was under the impression you had found a single or small number of lines of code where there's a _particular_ problem, or poor way of doing things, something to do with _finding units_... That should be a 1 line fix: Use the better method.

**Comment by Exotic-Retard** [comment]
another mod we want to blacklist under INTEGRATED is this gaz ui version:
e9bb4b11-2952-4b19-bf4e-11fb6e5fcbe9
got it from here: http://forums.faforever.com/viewtopic.php?f=3&t=13756#p141471

**Comment by CookieNoob** [comment]
Are you sure about UI Massfab Manager? It only adds new units to the list of Massfabs (thats stored btw) when the button "add all massfabs" is pushed, otherwise there is no checking of the massfabs. What could be improved is the way it turns off the massfabs (it cycles over the massfabs and turns them off one by one until the energy is sufficient instead of calculating how many massfabs need to be turned off and then just doing that). But thats certainly not enough to add it to the blacklist...
