### ISSUE TITLE
When observers are enabled, dead players goes to observers.

### ISSUE THREAD

**Issue by Tokyto** [FAForever/fa#1752]
Making observer feature unsusable for 2v2+ Tournaments streams.

**Comment by aeoncleanse** [comment]
This is the point of the option. I have no idea what your point is

**Comment by Tokyto** [comment]
The observer option should only affect observers, not players. For example, a live-streamer joins a 2v2 game to stream it, but gets kicked becouse the option is broken and dead people see whole map when they die, giving free intel to his teamnate.

**Comment by micheljung** [comment]
And the stream does not give free intel?

**Comment by Tokyto** [comment]
the stream can have a delay

**Comment by Tokyto** [comment]
This is mostly about caster+co-casters being in sync and people being able to use this feature in teamgames.

**Comment by Exotic-Retard** [comment]
livereplays for example have a 5 minute delay to prevent ghosting. when streaming a tourney you can get a 40s delay or so but point is that there should be a difference from observers who were there from the lobby and those who became observers after being killed in the game.

**Comment by aeoncleanse** [comment]
Unless I'm going insane, dying with Observers on sends you to a state where you can only see what your old team could.. You can act as an intel machine calling out stuff, but you don't get full-map vision... :/

**Comment by Exotic-Retard** [comment]
you are going insane i guess?
thats with obervers off, pretty sure anyway.

**Comment by aeoncleanse** [comment]
Right. Well, not sure what we can do about this... Or what people want even. New observer type???

**Comment by Tokyto** [comment]
If player dies, he doesn't go into observers mode. That's it i think.

**Comment by TheKeyBlue** [comment]
I think that we should add an option that says if dead players go to observers or if they stay in their own team view (default).
This way people can decide what they want.
Could be usefull for streamers like BRNK who maybe prefer to see the whole game after death instead of only his own team. (don't know what he prefers, but why not give him/others the possibility to chose?)

**Comment by Tokyto** [comment]
And FFA games could use this feature (to go into obs after death).

**Comment by duk3luk3** [comment]
The engine seems to be involved in this: The `SessionIsObservingAllowed` engine function can only be true or false (must be based on whether `gameInfo.GameOptions.AllowObservers` is set at init time?).

Then the ui module [`gameresult.lua`](https://github.com/FAForever/fa/blob/develop/lua/ui/game/gameresult.lua#L52-L54) switches users to observer when `SessionIsObservingAllowed` is true.

So since it's in the UI, it could be subverted by players.

To implement this, we would probably have to add a new boolean option "Dead players can observe" and if it's set to `false` just skip the `SetFocusArmy(-1)` call.

I don't know if it's possible to find out what the FocusArmy of another player is, but if it is, in a game with "Dead players can observe" set to `false`, all the other players could kick dead players who went to observer and that would fix our security issue with this.

Of course we could also ignore the security issue, we would then have to make sure competitive players are aware that it's a purely "advisory" setting.

**Comment by speed2CZ** [comment]
So simple fix would be to remove these 3 lines so the dead players can never move to observers. Would probably piss off some FFA players, but who cares.

**Comment by duk3luk3** [comment]
Like I said, it would be really easy to hack using a UI mod - Just put a button on screen that calls `SetFocusArmy(-1)` when clicked and then click it when you're dead.

(And I would really prefer we make it a lobby option instead of just removing it)

**Comment by speed2CZ** [comment]
From what I was trying I havent managed to use this function without cheats enabled.
