### ISSUE TITLE
Add loaded TML, Nuke into Idle Facs, Engies list in UI

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1756]
Responsible file https://github.com/FAForever/fa/blob/develop/lua/ui/game/avatars.lua

**Comment by aeoncleanse** [comment]
Errrm. What?

**Comment by speed2CZ** [comment]
on the right side of UI you have diplayed idle engineers, factories
if you click it it select it

Would be nice to show there loaded TMLs, Nukes, so it's easier to launch them

**Comment by aeoncleanse** [comment]
ohhhh. Yes, it would indeed. If you know how to, please do it :)

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse  @speed2CZ haha my new mod (not-release yet) is doing just that plus much more. Basically, it is complete overhaul of the avatars UI with a lot of configuration options such that a player can see status of all units or any subset of units. 

![image](https://cloud.githubusercontent.com/assets/11665978/21583014/61a59074-d03b-11e6-8579-ee8b7b73a3f0.png)

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse Actually, all unit icons (terrain images) have this edges cut off and you don't see it in construction UI or in the avatar UI because these icons are rendered over semi-transparent black background. You noticed this edges cut off in above screenshot only because I used gray background for testing purpose otherwise I'm planing to use the same background as rest of UI elements. 

![image](https://cloud.githubusercontent.com/assets/11665978/21752861/fcd0f058-d5ad-11e6-8acf-38a825793a7c.png)

You are right about minimal/default layout and it is on my TODO list. Also, I could integrate this mod to FAF but it would be an addition rather a replacement for the current UI avatars because my mod has almost nothing in common with the current UI avatars and players should have the option to choose either one of these UIs otherwise there would be 2 UI elements with overlapping functionality.

**Comment by Garanas** [comment]
Did that mod see the day of light? 😄 

Closing this issue as not planned, I like the feature but it is more for a mod.
