### ISSUE TITLE
ShieldCollider regressions

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1828]
so who removed the explosion thats supposed to occur on collision with the actual shield?
also can we not just remove collision from the transport category because uef t2 gunships are also in there.

as a result it means that transports (and czar and uef t2 gunships and exps) appear to fly right through the shield but theres a barely noticeable dent showing that the code actually works.

disappointed tbh.

**Comment by aeoncleanse** [comment]
Not including transports is a deliberate choice. UEF T2 Gunship not bouncing isn't. Getting some code for an explosion on contact might work, but an 'Explosion' might be too much... It should just do the same "I blocked something" ripple as when a shield blocks a projectile.

Also, would be really nice if you'd pay attention in qa-open-testing, because that's exactly where this kind of thing could have been pointed out and fixed low-latency :)

**Comment by Exotic-Retard** [comment]
the explosion has 2 purposes - 1 to make it obvious that something happened, shield ripple is clearly not enough since its completely obscured by exps and even the continental, also it has an explosion sound there too. i didnt use air explosions because if you look, those are shit. when a czar collides with sth hard enough to do 4000 damage to it i would think that theres an explosion, same as when a plane collides with something, like the ground and shields arent too different from that.
2 - to cover up the 1 tick delay in the attachment since its not instant, making the whole thing appear smoother

and yes it would be nice but for that i would need 2 lives worth of time xddd

**Comment by aeoncleanse** [comment]
5412e91c66f53c3cf71d0c86991c93db36d72140
