### ISSUE TITLE
AI using Engi Stations crashes the game

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1834]
http://forums.faforever.com/viewtopic.php?f=3&t=14056#p143782

**Comment by aeoncleanse** [comment]
One test completed. UEF vs Cybran, Sorian normal, Open Palms. Game time 38:08. 4 UEF T3 and one Cybran second stage stations constructed. No crash.

**Comment by duk3luk3** [comment]
Additional reports: 

* http://forums.faforever.com/viewtopic.php?f=3&t=14071 (also involves AI, unclear if engineering station)
* http://forums.faforever.com/viewtopic.php?f=3&t=14076

Probably unrelated:

* http://forums.faforever.com/viewtopic.php?f=3&t=14066 (1v1 without AI)

**Comment by aeoncleanse** [comment]
Original was error at 0x006cbc63, and he has since determined it's probably Brewlan that causes it.
Second was at 0x026ede58. Third was at 0x0231d261, fourth at 0x005f39f7...

Looks like a whole bunch. Could these all be caused by one thing, I dunno much about engine.

That last one belongs in https://github.com/FAForever/fa/issues/1574

**Comment by Uveso** [comment]
fixed: https://github.com/FAForever/fa/pull/1375
This can be closed.
