### ISSUE TITLE
Janus bombs tracking

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1864]
[5896243-JaggedAppliance.zip](https://github.com/FAForever/fa/files/819681/5896243-JaggedAppliance.zip)
In the replay you will see janus bombs tracking to targets over large distances(~30-60). The bombs only tracked when dropped while hovering. It is also possible to see this with uef t1 bombers but to a far lesser extent.

**Comment by aeoncleanse** [comment]
Dunno what could be going on, but it's not tracking... They are straight bombs, no tracking on them at all...

**Comment by JaggedAppliance** [comment]
@Exotic-Retard thinks it could be to do with this file: https://github.com/FAForever/fa/blob/develop/lua/sim/CalcBallisticAcceleration.lua

**Comment by Exotic-Retard** [comment]
its not tracking per se - its the bombs being fired when they should not be. the fix bomb trajectory just does what it always does and makes sure they hit the target ground they were aiming for, but again the issue is the bomber dropping when it should not.

we can disable the fix bomb trajectory script for cases like this but it would be a workaround i guess.

**Comment by aeoncleanse** [comment]
OK I glanced at it again, and now have seen the replay. I'm tired and writing this up so I don't forget, but I think I know what's happening:

The ballistics code is run one per bomb. When an enemy unit is in range, and you press stop, the unit (and hence weapon) will automatically acquire a new target as normal. Because the firing sequence is in progress, "local entity = launcher:GetTargetEntity()" will acquire the new target for the bombs, and calculate acceleration accordingly.

This can be confirmed by logging the entity ID and checking in the log if it changes half-way through one of the faulty bombing cycles. 

If confirmed, the fix will be to force the same target as bomb #1 for all subsequent drops.
