### ISSUE TITLE
Spin off {ui, lobby, sim} into own repositories

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#200]
This repo will become a meta-repo tracking these as sub-projects and handling central issue tracking, changelogs etc..

**Comment by MrRowey** [comment]
@Garanas Not quite sure what this is all supposed to achieve or even necessary now  ?

**Comment by KionX** [comment]
Separate patches for the UI looks interesting.
They do not violate the sim and can be released more often.

**Comment by Sheikah45** [comment]
I believe this is mostly for organization and tracking. As you could merge things into the sub repos and then make release by updating the version used in the main repo. Really it is just a separation of concerns preference.

**Comment by Garanas** [comment]
I think this would be interested if we had more people working on the repository with particular interests / experience. For example, if we had a few people dedicated to UI and a few people dedicated to sim. At the moment, I can think of only 3 - 5 people who are working on the repository at all from a developers perspective - this additional overhead (of both the setup and working with it) doesn't seem worth it because of that.

I am closing this issue unless there is an objection.

**Comment by KionX** [comment]
Here is a clear example of the simplest fix that is waiting for 4 months. Because the UI is not updated separately. #3401

**Comment by Garanas** [comment]
And I still disagree. 

The real issue is not that we do not have several repositories, it is that it is a year ago that we had a patch at all. I'm going to try and introduce a bi-monthly patch after the current patch - that will solve this issue too.

**Comment by MrRowey** [comment]
@Garanas  Possibly close this off as your aim to do more regular updates to the game as 3-5 people working on the repo is all were probs ever going to get at one time
