### ISSUE TITLE
Mouseover of any unit's icon in the construction section shows costs/costs per second in detail view as if it could build.

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#2005]
Introduced in https://github.com/FAForever/fa/commit/7f1e2f536a166c330da2bdb7c803c0c65ac7be0a

**Comment by Uveso** [comment]
That's true :)

Normal tooltips and normal unit overview are created inside `unitview.lua`.
`unitview.lua` is using as database for the tooltips the function `database = GetRolloverInfo()`

GetRolloverInfo() only works if on mouseover a unit inside the mainview not on a construction bar.
Also the arrayindex we get from GetRolloverInfo() is not formated in camelcase like blueprints (first letter is lower-case)

```
Index[entityId] is type(string). "\000"0"\000".
Index[armyIndex] is type(number). "\0000\000".
Index[blueprintId] is type(string). "\000"uel0001"\000".
Index[energyConsumed] is type(number). "\0000\000".
Index[customName] is type(string). "\000"Uveso"\000".
Index[fuelRatio] is type(number). "\000-1\000".
```

Detailtooltips and overview are created inside construction.lua.
Here we are using UnitBlueprints as database for the tooltips. And they have another format then data from GetRolloverInfo()

```
Index[BlueprintId] is type(string). "\000"uel0103"\000".
Index[Categories] is type(table). I won't print that!
Index[AverageDensity] is type(number). "\0000.49000000953674\000".
Index[Source] is type(string). "\000"/units/uel0103/uel0103_unit.bp"\000".
Index[SelectionMeshScaleY] is type(number). "\0001\000".
Index[LifeBarRender] is type(boolean). "\000true\000".
```

So our first problem is, we can't use the Data from a blueprint.
Sure we can convert names like `BlueprintId` to `blueprintId`, but we can't add missing data like `entityId`, `customName` or `armyIndex`.

Then we have the problem, that we can't simple call the function for creating a normal overview from `unitview.lua`.
The tooltip is here generated inside an 'onframe function' and can't be called as single function from outside.

We also can't simply deactivate the overview, because we need it as anchor for the tooltip.
And we can't "not refresh" the detailview, or we will not display the actual unit but a unit that we selected before.

So i dont know how we should fix this.

Lets say it's a feature that we can see the detailed overview, not a bug :)

**Comment by aeoncleanse** [comment]
Bug isnt the overview, its that things like mavor and pgens show not only their cost to build, but also a rate in brackets as though they could build something themselves, and a completion time
