### ISSUE TITLE
Revert Energy storages on pgen hotbuild key

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2008]
Please. It's not worth the risk of accidentally building them, they are rarely built and can be hotkeyed in other ways already.

**Comment by speed2CZ** [comment]
Yeah this is pretty dangerous, I dont think E storage is built so often in a game to be on the same key as pgens

**Comment by aeoncleanse** [comment]
I checked and it is end of queue... Shouldnt have been such an issue imo

**Comment by TheKeyBlue** [comment]
Well hydro is on the same key, and thats not build that often either. Mostly at the start of the game when people have all the time in the world.
Isn't it mostly an issue cause people don't know about it?

**Comment by aeoncleanse** [comment]
I get a definite knee jerk feel from this

**Comment by JaggedAppliance** [comment]
You can't accidentally build the hydro though keyblue. As I said, you can already bind energy storage to a hotkey. It is rarely built. It is also the same size as a t1 pgen so it is very easy to miss your mistake if you start building them. The pgen hotkey is one of the most often used hotkeys in the game so it doesn't make sense to have some like energy storage mixed in there, its only relation is that it has energy in the name.

**Comment by speed2CZ** [comment]
Yeah you wont accidentally build line of hydros that will lose you the game

**Comment by Pacozcz** [comment]
you wont also accidentaly build line of storages that will lose you the game...this is briliant idea e strogae is so easy to diferentiate I cant imagine anyone mistaken it for pgen really

**Comment by JaggedAppliance** [comment]
I've already seen it happen early on in 2 games and if you even build 2 of them by accident it's 500 mass so you are fucked.

**Comment by Pacozcz** [comment]
well what can I say them ppl are blind then :-D its hard for me to believe it can be mistaken...still think its good idea

**Comment by tatsujb** [comment]
this is idiotic.

**Comment by TheKeyBlue** [comment]
Please be constructive, my friend.....

**Comment by tatsujb** [comment]
okay I meant I don't see this as an issue

**Comment by hoclun-rigsep** [comment]
Just adding my 2¢ to say the storage should stay there. One seldom has to cycle through these options with multiple keypresses. Almost always, you just want the highest-tech pgen you can build, which still takes just one keypress. I don't understand the circumstance where you are trying to press this button four times to build a pgen instead of once and end up accidentally building storage.

**Comment by MrNukealizer** [comment]
There are two main situations where you'd accidentally build it. 1. When queuing T1 pgens after a hydro. 2. When making T1 pgens for adjacency purposes. I've lost 3 games to those mistakes and once had a T3 artillery installation surrounded in energy storage because T3 pgens would be too dangerous. I ended up making a whole UI mod just for the purpose of removing that from the hotkey.

**Comment by JaggedAppliance** [comment]
Another game ruined by this: 6345964

**Comment by hoclun-rigsep** [comment]
At least assign this to another building key where it cannot be mistaken for a phenomenal. It is nit enough that one can map this to a key by itself because that takes away a whole key. It would be different if a key could be mapped to multiple functions (then I would have, for example, launch missile and launch nuke mapped to the same.key) but as it is it sucks to have to dedicate a whole key or chord to the power storage. For people with shit mouse skills like me every key counts.

**Comment by JaggedAppliance** [comment]
By all means put it on a different key, but it has to be removed from the pgen key.

**Comment by aeoncleanse** [comment]
Done in 3686
