### ISSUE TITLE
Collection of formation issues

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#2040]
Here's a place to keep track of problems with the current formations that might need work:
Edit: list moved to PR #2073.

**Comment by PhilipJFryFAF** [comment]
If you change the t3 sub you might want to watch for where it ends up in the formation to avoid it taking damage from surface units getting hit by projectiles with enough aoe to harm a submerged sub

**Comment by Exotic-Retard** [comment]
actually i think thats optimal behavior - the issue with the t3 sub is a separate one and can be addressed separately as well, while in terms of formation any t3 subs need to be at the front (otherwise they cant fire their torpedoes), and t3 strategic subs need to be at the very back, while the cyb one should be somewhere at the back middle since it has torpedoes.

in any case high level games involve a lot of micro which separates the subs.

it would be cool if the subs were offset by half a unit width so they are not under the ship directly but in between them, it also makes it easier for strategic icons. but im not sure how difficult that is

**Comment by MrNukealizer** [comment]
It shouldn't be too hard to remove one column of subs to stagger them between the surface units.

**Comment by MrNukealizer** [comment]
Status update: I've been digging around in the formations a bit and there's a lot we can do here. All the stuff on the checklist is doable, but we can also make a lot of more significant changes if needed, such as adding new formations, changing the shape of existing formations (like making air formations actually useful) and more.

**Comment by speed2CZ** [comment]
We should spread out the air formations a bit, so the air units wont get killed by flak and sams so easily

**Comment by MrNukealizer** [comment]
Status update: After a couple failed attempts at fixing unit spacing I've come up with [this](http://i.imgur.com/Lkdsj6Z.jpg), which looks promising. Now to make it work for naval units and tackle the other problems.
