### ISSUE TITLE
cheat pannel issue

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2058]
![image](https://cloud.githubusercontent.com/assets/11618427/26793343/ee038984-4a1d-11e7-88e6-6bbcfc1539ad.png)
select a specific button (like land)
![image](https://cloud.githubusercontent.com/assets/11618427/26793351/f629c5d8-4a1d-11e7-8163-5d57b83e655f.png)
un-x the category where the button belong to
![image](https://cloud.githubusercontent.com/assets/11618427/26793359/fca982ae-4a1d-11e7-8213-7d3eb17f32bc.png)
x it again, the specific button is now active again, but doesn't show up as active.
![image](https://cloud.githubusercontent.com/assets/11618427/26793419/378cc386-4a1e-11e7-9406-d9744ec72cbc.png)
need to click on it once again to make it appear ative (even if it was active before)
![image](https://cloud.githubusercontent.com/assets/11618427/26793435/4b59acc6-4a1e-11e7-9de2-75ac54aa26ab.png)
and click on it again, to finally disable it.

**Comment by HUSSAR-mtrela** [comment]
closing because it is not UI issue because there is no way to know which button(s) should be enabled when checking the Type checkbox. Un-checking the Type checkbox simply clears out any options selected next to it.
@shalkya Try opening the cheat menu for the first time and checking the Type checkbox. Do you expect to see Land, Air, Naval, or Base button highlighted or maybe all of them?

**Comment by shalkya** [comment]
hmm, seems weird that we can't know which buttons was enable before you click the box.

otherwise to answer you, i would say all of them. (but then obs you need to show all unit when you check that box)
