### ISSUE TITLE
hp boost (abuse?) with upgrade

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2068]
for example i've double nano on ACU, and i go down 1000 hp for example, if i remove the nano upgrades, i go down to 1 hp (since it remove 26k hp from what i have, but i can't have negative hp, so in the end i only lose 1k hp). When i upgrade the nano upgrade, i regain 26k hp.

So i just regained 25k without repairing (doesn't work on acu) / regening. 

Is it intended or not ?

**Comment by aeoncleanse** [comment]
"Intended" gameplay probably.... not. "Intended" code wise, yes. There is no alternative that doesn't cause far worse issues, several of which we discussed.

**Comment by Exotic-Retard** [comment]
this would work the same way if you didnt have any upgrade and just upgraded one in the first place, i dont really see the issue here. the hp boost is the same from that no matter what. however this should be actually solveable since you just change the buff flag to donofill on there. then upgrades simply dont give you any current hp and just max hp which you need to regen, in any situation

**Comment by shalkya** [comment]
exotic this is not totally true.
if i remove my 2 nano while have 30k hp, i will end up with 4k hp.
if people use that hack to regen faster, then why not create another upgrade that allow people to just pay for hp boost ? I mean at least that wouldn't be hacky, and everyone would know that. (i'm not really for this upgrade, but at least it show you how dumb it is)

**Comment by Exotic-Retard** [comment]
what i said is totally true you just misunderstood. if you are on 1k hp with no upgrades and get double nano you get 26khp, and it doesnt matter if you have the upgrade before or not. its just in this case its not really counted as abuse either way, but does the same thing pretty much.

likewise i dont think that you want to pay 6k mass to regen that much since you can just wait and get it back for free in a similar time cos you already have double nano

**Comment by shalkya** [comment]
nah i didn't misunderstood.
you completely ignore the fact that you lose the hp when you remove the upgrade if you have enough hp (what i said before). So you CAN'T compare it to having no upgrade before, OR we make remove upgrade not removing health (only max health), then it is perfectly fine, there is no hack using the fact that you can't have negative HP.

well all depends of your eco, the urge of getting HP back, i agree in most case i would wait, but there can be situation of abusing this hack can impact the game.

**Comment by aeoncleanse** [comment]
The point of these upgrades is you pay mass and energy for HP. That doesn't change. This isn't abusable to any real degree. You're just paying for a second thing of HP.

I refuse to believe that after 10 years this is suddenly a problem.

**Comment by shalkya** [comment]
well ok, i just had to correct exotic, but i agree if fix bring more issue, it's not worth solving.
