### ISSUE TITLE
Drones are not restriced by "no air"

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2083]
drones are air units but they are not affected by the "no air" unit restriction
not 100% sure if we want to change that - just wanted to point it out/make an issue for it
would make a lot of sense though since mobile/static aa is disabled by that option as well so getting rid of drones is pretty hard with the "no air" enabled

**Comment by ChrisKitching** [comment]
Last time I looked at this (2-ish years ago) the behaviour was that "no air" allowed drones, but didn't ban flak (so you could build anti-drone towers easily enough)

**Comment by MrNukealizer** [comment]
In the current version the no air restriction removes all air units except drones and everything specifically used for AA or supporting air. That means no air factories, AA turrets or units, air staging, and I think no Aeon or Cybran carriers. It effectively means the only units left to counter Kennel cheese are Cybran SACUs (I don't think the missile upgrade is restricted but it might be.), naval units, and experimentals. I once had to build a pair of Ythothas for drone defense in a no air game.

**Comment by ChrisKitching** [comment]
That seems silly. I don't see why mobile AA, flak, etc. shouldn't be allowed in a no-air game. There's probably an argument for using them as cannon fodder, too (and some of the mobile AA can engage land units anyway).

Deleting drones seems like it'd cripple UEF/Cybran's ability to build stuff late-game?

**Comment by ChrisKitching** [comment]
I'm also reminded of a fun bug I introduced at one point. People were using various tricks to construct disabled units in games with restrictions. So I added a little callback a few seconds after a unit spawns that makes it blow up if it's restricted.

This worked great at stopping cheaters, but it turns out that some people play "no land units" games.

The ACU is a land unit.

The practical result is when you started such a game, your ACU exploded about 10 seconds in for no readily-apparent reason. :D

**Comment by aeoncleanse** [comment]
The entire reason for our comprehensive unit restriction manager is to make pointless issues like these. Drones are not blocked by default in no air because it removes an engineering option late game. The option refers to proper air-theatre units. 

If a player wants to restrict drones too, its merely a click away. Oh, and as the preset selection gives a visual indication of units affected there is no excuse :p

**Comment by PhilipJFryFAF** [comment]
just got a report from some user who complained about his stuff getting reclaimed by uef drones in a no air game

imo the drones should not be available in no air games and the unit restriction for no air should reflect that
will take a look at the restriction manager and create a PR

**Comment by ChrisKitching** [comment]
I mean, IceDreamer explained it pretty well above. You can set it up however you want.

- Turn off drones?
- Turn on drones, but also turn on mobile AA so they can be insta-killed?

... Something else?

**Comment by FlyingThunder** [comment]
This is still an issue - disabling the drone com upgrade does not work! Disabling the Kernel does work, but you can still build UEF com drone when disabling the upgrade!

**Comment by KionX** [comment]
I believe that as it is now so and correctly.
This issue should be closed.

**Comment by shalkya** [comment]
right now, drones aren't restricted by "no air".
But right now, it is allowed to make AA again with "no air" activated, to shoot down the drones.
