### ISSUE TITLE
disable mod only for certain game mod

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2107]
for example would it be possible to disable automatically let's say "notify" for develop, but when you host a normal faf, having them enable again.
As if develop pause certain mod, but this mod don't need to be re-enable when joining a normal faf.

**Comment by CookieNoob** [comment]
the game could just not save the UI mod settings that are changed in the lobby to the game.prefs file. This way only the UI mods that are set in the mod vault (manage UI mods) are persistent and thus blacklisted mods are automatically enabled when you host a game mode where they are not blacklisted.

It's not ideal since they always show this popup "a mod is outdated/..." when you host or join a game with develop and more importantly, after a faf update everyone would have to manually disable the blacklisted UI mods in the management window.

A better solution could be to not save the mod selection if the hosted game mode is develop.

**Comment by CookieNoob** [comment]
as it turns out, the way that mods are handled is not optimal... anyway, develop can be excluded from changes of the mod list by adding this
```
        if not GetCommandLineArg("/init", 1)[1] == "init_fafdevelop.lua" then
            SetPreference('active_mods', s)
        end
```
at line 216 of lua\MODS.LUA (instead of `SetPreference('active_mods', s)`)

HOWEVER due to this, you cant change your UI mods at all when hosting develop (sim mods work fine). I'm not sure we really want this.

**Comment by aeoncleanse** [comment]
I agree with cookie. The solution is here should someone want to use it locally.

**Comment by shalkya** [comment]
is this the only solution ? doesn't seems to be better than actual situation.

**Comment by aeoncleanse** [comment]
It's just not really an issue. Devs who want to use this solution can use it, those who don't... doesn't matter. There's no reason to spend time coming up with some complex solution for main code. Just stick this in a mod is probably the best bet.
