### ISSUE TITLE
com stop firing for periods of time

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2125]
guess it's linked to some OC cancel at very last moment, leading into issuein reloading. But that's only some random thought. 
http://forums.faforever.com/viewtopic.php?f=3&t=14912&p=152489#p152453
replay and logs in here.

might also be linked to auto OC.

**Comment by MrNukealizer** [comment]
This might be fixed by #2063 but I'll look into it.

**Comment by MrNukealizer** [comment]
Yeah, I'm about 80% sure #2063 fixes it. I'm not entirely sure what went wrong, but running the replay with  that change fixes the behavior. Unfortunately it also causes a desync much earlier so it's hard to be completely sure that it fixes the problem instead of just changing the circumstances so it doesn't happen.
