### ISSUE TITLE
Feature: Adjust minimap height according to the playable area

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2189]
This would be mainly feature for coop as that's the place where you usually find a playable area that is not a square.

So the idea is to keep the width same as player sets it and adjust the height to fill the minimap completelly.

This would be adjusted each time the playable area changes.

**Comment by Uveso** [comment]
Please make this with an option.
My map needs a fixed height/width, because it's surrounded from other icons.

**Comment by MrRowey** [comment]
@Garanas Move to Coop

**Comment by Hdt80bro** [comment]
We're already adjusting the map size to the playable area in the score panel, so all we'd need to do is move that change listener to a more central place to get the minimap working (since score.lua doesn't create a UI for the campaign, hooking in there won't work). I've already worked up a playable-area change callback system that'd sit in gamemain.lua and also got functioning callback methods to attach from the score panel and minimap, but... I mean, it all seems a little over-the-top to support two features that (a) won't ever interact on any map I've seen and (b) already won't be used very much.

**Comment by Garanas** [comment]
I agree - it is a bit much.
