### ISSUE TITLE
Cannot select wall sections with double clicking on one of them

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2292]
**Steps**:
- build a few wall sections
- double click on one of wall sections

**Actual**: selections of just one wall section
**Expected**: selections of all wall sections

**Reason**: double clicking to select units of the same kind works on all other structures except of wall sections. Also, this

**Comment by FAETHER** [comment]
To keep this documented, the problem lies in the 'WALL' flag that is found inside units BP. There is no way to modify the flag make a script for double click (is handled by the engine). The only way is to remove this flag, however the ai scripts use this flag for references and that will cause extra problems. So far this issue is hitting a dead end.

**Comment by FAETHER** [comment]
Additional info:
If somebody will try to make a script for this here is good place to start. 
file: construction.lua in function OnSelection (...) line 2435
` local register = 0`
`for i, v in selection do`

		if v:IsInCategory('WALL') then
		    register = register + 1
			WARN(register)
      -- in here should be some sort of delay to simulate double click. WaitSeconds(...) will not work!
                register = register + 1
      --        in here code that will calculate time between clicks. 
		end
		if v:IsInCategory('WALL') --[and Timebetweenclicks >= ? --] then
      -- here function like GetSimilarUnits() from misckeyactions.lua
		end	
`	end	`

/// Signing Kyryl Melekhin ///

**Comment by Sheeo** [comment]
Deployed for current FAF version.
