### ISSUE TITLE
kennels classified as sensors

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#2300]
Kennels (XEB0104 and XEB0204) have General.Classification property set to RULEUC_Sensor.  Bug?
Hives on the other hand have RULEUC_Engineer which seems to make more sense.

**Comment by speed2CZ** [comment]
What does this affect?

**Comment by spooky** [comment]
Well, in the game - no idea :D, it does however influence the unit db.

**Comment by Uveso** [comment]
Please check, that those chages don't trigger the old "EXCEPTION_ACCESS_VIOLATION (...) at address 0x006cbc63 #1375" Error.

**Comment by speed2CZ** [comment]
It doesnt change the categories. I dont actually know where (if at all) the game uses the values I've changed.

**Comment by Uveso** [comment]
The problem was, that the mainengine crashed if a hive was executed with the PlatoonTemplate `EngineerBuildAI` and `TransferAI`.

It's not clear why it actual crashed, but it has something to with constuction units that are unable to move. (In case the constructed unit is outside build range)

Having this in mind, i am just not sure how the kennel will react, since they are now also 'RULEUC_Engineer'.

Theoretical the kennels will be fine, because they are also filtered by ` - categories.ENGINEERSTATION` inside the platoontemplate.
But i am not sure because of the drones.

I will test this today/tomorrow.

**Comment by Uveso** [comment]
I did some tests and got no errors so far.
Looks good!
