### ISSUE TITLE
Add banned maps

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2337]
We have a blackist of maps but it doesn't prevent them from playing, only hides them in obsolete maps. It would be nice to have a way of preventing launching certain cheat maps.

I can unrate and hide maps from the vault, but that doesn't prevent downloading them if someone who has the map already hosts it.

**Comment by CookieNoob** [comment]
I think the best way would be to do this server side and simply not show the lobby in the games list if the host selects a cheat map. This doesnt stop them from hosting a different map and when the game is full, swich to the cheat map. However, in that case, most of the players in the game dont have the map and thus need to rejoin (impossible since the game is not displayed).

**Comment by speed2CZ** [comment]
Lets imagine for a second that any server work won't happen in the near future :D and work with that.

**Comment by CookieNoob** [comment]
any game/lobby related code can be changed locally though

**Comment by shalkya** [comment]
and what if one of them host the map while not knowing it's forbidden ? Then he will think there is a bug since his lobby doesn't show etc... I already have to show obsolete to play maps like badland, since it had been put in obsolete for some reason. Chances are that other may do likewise, but will cheat maps.

**Comment by Garanas** [comment]
This feature is quite niche - I understand the need but it is rarely an issue.
