### ISSUE TITLE
assist on cybran shield cost too much

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2383]
the price is 4 times higher or so.
![image](https://user-images.githubusercontent.com/11618427/36426251-3618d53c-1695-11e8-93a4-2eb34255b521.png)
![image](https://user-images.githubusercontent.com/11618427/36426258-3cbc70e2-1695-11e8-8b65-c1d9427ac0eb.png)

bets are that it is due to the upgrade on cybran shield.

**Comment by shalkya** [comment]
replay : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7527720
log : 
[game.log](https://github.com/FAForever/fa/files/1747691/game.log)

**Comment by JaggedAppliance** [comment]
Does it repair the shield at different rates? It may not actually cost more, Cybran shields have a much lower build time than other shields

**Comment by shalkya** [comment]
i don't really understand what you are trying to say.
Anyway the repair of the shield (not the structure) goes as fast as the other, only the price is 4 times higher.

**Comment by JaggedAppliance** [comment]
Can you try doing the same test but with the ED3 and ED4 shield in beta?

**Comment by shalkya** [comment]
With FAF beta :
ed 1 : ![image](https://user-images.githubusercontent.com/11618427/38408132-8fc3bf28-39bf-11e8-8e58-0044768ba675.png)
ed 2 : ![image](https://user-images.githubusercontent.com/11618427/38408218-e8b6cc60-39bf-11e8-87ce-ec0bc39d440f.png)
ed 3 : ![image](https://user-images.githubusercontent.com/11618427/38408003-10e78806-39bf-11e8-9d85-2bbe6c9c6eac.png)
ed 4 : ![image](https://user-images.githubusercontent.com/11618427/38408024-24e9da8e-39bf-11e8-9e4e-7a32342329da.png)
ed 5 : ![image](https://user-images.githubusercontent.com/11618427/38408242-0554fcde-39c0-11e8-8242-5bff479eec8a.png)

as comparison : 
T3 aeon shield : ![image](https://user-images.githubusercontent.com/11618427/38408188-cc661138-39bf-11e8-9f30-f7c8acd4172f.png)

it's now less pricey for ED 4, which mean there is something fucked with all this upgrade added on top of each other.

**Comment by JaggedAppliance** [comment]
Seems like it's got to do with the buildtime of the shields. Cybran shields have low buildtimes compared to others. I had to increase the buildtime of ED4 when making it buildable by T3 Engineers. Strange that it repairs the shield to about the same degree though

**Comment by shalkya** [comment]
if we reduce price of the upgrade, the assist cost less.
if we increase the BT of the upgrade, the assist cost less, but it won't impact the speed of regeneration of the speed.
fix is in 2 part : 
1st : make the regeneration speed scale up to the BT
2nd : make the regeneration speed and cost take into account the price and bt of all previous upgrade. eg : the assist on ED3 cost will depend on the ED1+ED2+ED3 upgrade cost and bt.

**Comment by zlo-faf** [comment]
Copy pasted from balance discussion
![unknown](https://user-images.githubusercontent.com/14075326/53888702-3b5ef000-4036-11e9-9b1e-3bec50c45ed4.png)
drain is proportional to  resource / BT
regen hp/s is proportional to natural shield regen ( divided by 60 )
some values are fucked for cyb shields cause ED5 has low BP so hive drain alot more when assist it
ED5 has low BT cause ED4 has low BP
so some one some time ago decided to lower ED5 BT instead of increasing ED4 BP
or maybe it is ed4 that is fucked...
because ed3 has higher than usual BT...
so ED4 is better than other cyb shield...
bad news that right now you can't change drain without changing cost or BT and can't change regen effectiveness without  changing natural regen

**Comment by shalkya** [comment]
fixed in #2703
