### ISSUE TITLE
Lobby - > Get Avatars (Rating/Game count) via GPGNet

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/fa#2520]
Currently rating and game count can be manipulated extremly easy. As discussed in slack this gets pretty dangerous with the new avatar system when a person is e.g. able to imperson a moderator/councillor.

If it's possible to grab data off of GPGNet we should switch the entire system to injecting this data from the client which retrieves it from the preferably api / server itself.

**Comment by PhilipJFryFAF** [comment]
grabbing the info from the local client is not good enough per se
there needs to be a check with the db from other players/at least the host to see if the info that other clients send adds up with what is stored in the database

**Comment by Geosearchef** [comment]
Not there need not be such a check. Just throw away everything a different client sends and get ALL avatar, rating and game count data from your own client.

**Comment by Super4121** [comment]
Are you saying that only the host can know the rating and all the other information? And he will receive with the help of his client? And then spread between the players who went to him in the game.

Just why compare the information when you can do so, so that only one could learn the data ( Reliable source, that is the host.)

**Comment by Garanas** [comment]
The avatars never made it into the game. We shouldn't anyhow - keep those in the client.
