### ISSUE TITLE
no naval restriction includes wrong units

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2563]
no naval unit : shouldn't remove ~naval factory and~ torpedo defense
![image](https://user-images.githubusercontent.com/11618427/43714413-29644446-997d-11e8-8291-6b4e4c7cb367.png)

**Comment by HUSSAR-mtrela** [comment]
@shalkya IMO it should remove naval factories because they will not be able to produce any naval units.

**Comment by shalkya** [comment]
the same way as for land factory, they will still produce engineer.

**Comment by HUSSAR-mtrela** [comment]
@shalkya I disagree with allowing naval factories when No Naval restriction is enabled because these naval factories will be useless. Also, we restrict air factories when No Air restriction is enabled so we should do the same thing for No Naval restriction. By the way, why did you reference PR# 2509 in this issue? I mean PR# 2509 has nothing to do with unit restrictions.
