### ISSUE TITLE
Wreckages under water create a smoke effect

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2617]
When a ship or a plane sinks down and create a wreckage at the sea bottom the smoke effect is created on the surface, which looks bit dull.

This should be the code responsible for it:
https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L1655-L1656

Looks like simple condition for checking the layer should do the trick.

**Comment by PhilipJFryFAF** [comment]
can you make a screenshot showcasing the issue?
imo it doesn't matter since the unit dies on the water surface and the smoke is created there

once the dead unit starts sinking the smoke already starts to disappear which adds up
what bothers me more is smoke from units under water that are being shot at (eg an amphibious unit getting hit by torpedos)

**Comment by speed2CZ** [comment]
Currently what happens is that unit is killed over water, air or navy, it explosed, starts sinking. Once it hits the bottom and turns into a wreckage a magic smoke effect appears on the surface

**Comment by PhilipJFryFAF** [comment]
ok now i got it
tested your PR locally and it works (no more smoke effect on the water surface from a wreck on the bottom of the ocean)
