### ISSUE TITLE
Big units occasionally get stuck inside unwalkable terrain

### ISSUE THREAD

**Issue by sernikb** [FAForever/fa#2635]
So this just happened:
https://i.imgur.com/sxAWmoi.mp4
Experimental unit got stuck on unwalkable terrain with no hope of getting out.
Since its game breaking, even a simple unstuck code when units are on this type of terrain
could be very helpful.

Replay UID : 8738949

![forgedalliance 2018-10-25 23-35-38-25](https://user-images.githubusercontent.com/20167348/47533163-04701500-d8b3-11e8-9083-3a140458af53.png)

Related issues:
#2400 
#784

**Comment by Garanas** [comment]
This is engine related, as Uveso mentioned in one of your references to other issues and I don't think we can interfere with that easily. 

A solution to the symptom that can help is to use the terrain types that are unwalkable to help smooth out the bits and pieces of the terrain that are intended to be unwalkable. As an example:
<a href="https://ibb.co/ZmtL4s3"><img src="https://i.ibb.co/3zGr6Xw/example2.png" alt="example2" border="0"></a>

The red bits are marked unwalkable because the terrain determines it is. This is very spotty and causes all kinds of issues. The slighly darker bits are pieces of terrain on the mountain are  marked by the developer as unwalkable. This has a smooth edge and it helped prevent platoons getting stuck when they walked closely to the mountain (one unit ends up being stuck, causing the platoon to halt and wait). The Ozonex editor clearly marks the two terrain types that are unwalkable, from the top of my head its ground9 and lava.

**Comment by MrRowey** [comment]
@Garanas unfixable tag and close
