### ISSUE TITLE
area enemy selection for an attack order

### ISSUE THREAD

**Issue by rjy7wb** [FAForever/fa#2716]
for example, 

I have a large(r) group of fighters and my enemy has a group of their own, for efficiency I want to group select their group, and spread attack so i can avoid overkill and the time it takes to switch targets.

currently i would have to click on each small, moving enemy plane individually which is hard to do, and it feels like this "should" be a feature.

**Comment by shalkya** [comment]
https://www.youtube.com/watch?v=MGjYqpTLMOo
mod is already done, balance decided against.

**Comment by rjy7wb** [comment]
this is beautiful, one problm i've noticed is unknown units have a smaller selection radii compared to normal units, i wanted a way to efficiently task orders out for my fighters.

**Comment by shalkya** [comment]
This would reduce the limitation of the game. Although it will impact the balance, some unit like bombers / torpedo bombers will get a huge improvement.

**Comment by rjy7wb** [comment]
area selection should apply to enemy units aswell as your own.

for instance, drag and select your group then drag and select a group of enemies while holding some hotkey and boom each of your units has a target on theirs.

it shouldn't effect balance, as you aren't "microing" just more efficiently giving orders.

**Comment by shalkya** [comment]
you didn't read what i wrote. Some unit would get way better with this kind orders (wrote up some example above.)
ie, going navy would then maybe not worth it at all.

**Comment by rjy7wb** [comment]
thats interesting to think about, it would buff cruisers, as countering bombers would then take priority and also buff inties/asfs too.

I think it would improve the UI/UX as managing large armies is a huge hassel atm

**Comment by shalkya** [comment]
the issue here is that this buff is better for the torp bomber than for the navy. 1st because the torp have the engagement advantage and also because rn after the first voley, cruiser tend to spread the split their attacks nicely, while it's the opposite for torps. (we can already split the first voley in a okish way, but then torp tend to overkill a lot)
So it would require other changes like nerf torp or buffing cruiser, frig aa. But it's not that simple, because torp would be not as good in early navy (if nerfed) and buffing aa would make navy stronger against T2 gs for example (that doesn't need splitting, since they can focus fire nicely and switch to another vessel).

**Comment by Garanas** [comment]
@Tagada14 is the balance team still against? If so, you can close this issue.
