### ISSUE TITLE
System message broken

### ISSUE THREAD

**Issue by Xinnony** [FAForever/fa#276]
With merge this https://github.com/FAForever/fa/pull/223

Now the 'Show system message' in 'Lobby Options' not work if i uncheck this.
Revert please.

**Comment by aeoncleanse** [comment]
It's not that commit which has done it, because those xngine strings are not called or referenced anywhere. Not saying it's not broken (Have not checked) but I don't see how it can be this one.

**Comment by aeoncleanse** [comment]
I checked now, system messages are working my end, auto teams settings are displaying properly.

Oh, and I'm gonna be frank this time: Instead of acting like an indolent, petulant arsewipe, try explaining why it is you think that the removal of these strings, which are not referenced at all, is going to have any effect? That's how adults behave when they have an issue.

**Comment by Xinnony** [comment]
System Message not worked for Connect/Disconnect message.

**Comment by Sheeo** [comment]
He means the system messages can't be _hidden_. I have yet to verify this myself.

**Comment by aeoncleanse** [comment]
Oh yeah... Odd that. Still, it's not the commit he pointed to.

**Comment by Xinnony** [comment]
I create the script for hide the Connect/Disconnect message, i know whereof I speak as well !

**Comment by ChrisKitching** [comment]
After a quick glance at this, it looks like the problem might be something to do with the way this:
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L4514

seems not to be checking SystemMessagesEnabled before printing. Thoughts?

Let's simplify how we check for enabledness, properly define what a "system message" really is (and which ones we want to suppress) and do it all from ShowSystemMessage. This probably warrants some discussion with the rest of the team: Do we really want to muffle events like "user timed out"? People plausibly want to be able to observe the difference between someone disconnecting and someone being kicked (though I realise that this presently is impossible either way)

#279 is probably in about the right direction. Haven't tested it, but, hey, it's 3 in the morning. Hopefully it'll at least push the discussion in a productive direction.

**Comment by ChrisKitching** [comment]
@Xinnony: In response to your comment about trust: nobody should be a "trusted developer". Everyone makes mistakes, especially in software design: that's why we have code review. Even highly experienced developers still submit code to each other for review because they're aware that they make mistakes (really, really often, it turns out.).
I've probably got at least one amusing mistake in my latest PR. These errors are a big part of why they're "requests": it allows reviewers to spot the mistae before it starts ruining their life. This is just how things go.
As a result, if you work in software you'll be miserable if you get upset/offended by people politely (or possibly somewhat bluntly) doing any of the following:
- Pointing out a mistake.
- Incorrectly accusing you of having made a mistake (they're just making a mistake).
- Being told that you're incorrectly accusing someone else of making a mistake.
- Having a mistake you made in the past ago fixed.

Nobody thinks any less of you because of this. People don't look at a PR that fixes a bug and think "The person who wrote the original code was stupid", they think "Oh good, the program will stop crashing now".
The amount of amusingly broken things that end up in software projects is hilarious, but if any one developer is "trusted to get things right" then the error rate goes way, _way_ up.

It may yet transpire that there's some magical C++ code hiding in SC.exe that makes my commit from #223 incorrect. That'd be sort of awful coding by GPG, and it'd definitely mandate some documentation on our side, as it would mean we probably can't do things like rename "AddChatText" without breaking the universe. I tried to get your side of the story at the time, but you just shouted at me.

I am trying really, _really_ hard to establish a productive dialogue with you, @Xinnony. For this to work, it will be necessary for you to do more than just shouting abuse whenever I suggest something that offends your ego. You never put forth technical reasons to take a different path, you just rant at me for having the audacity to question your divine perfection. It is absurd.

Ultimately, the only person who suffers in this scenario is you: you might have entirely valid reasons for my proposals to be dropped, but if you never voice them then you don't really get to complain when something goes ahead.
With with me, @Xinnony, or you are going to get left behind.

**Comment by Xinnony** [comment]
k.
