### ISSUE TITLE
Beam weapons aren't visible when instigating unit is out of intel range

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#29]

**Comment by Crotalus** [comment]
Is there any clever way of solving this? Maybe make beams / instigator visible if they are hidding at something owned by an ally?

**Comment by aeoncleanse** [comment]
We're getting closer to this right? If Chris can get a PR which has his solution, but for mobile sources only, I say we merge that into 3641

**Comment by ChrisKitching** [comment]
I have code that can do what Crotalus suggested: make the instigator visible when it's hitting a friendly unit.

This is slightly problematic, because for buildings it creates a persistent intel blip, so it can now be targeted.

Some more work revealed a way of, for mobile units, only showing the actual beam itself. It's an awful hack, but it's computationally cheap. This should probably be merged to make the user experience when having your face melted by a surprise monkeylord.

Since the only non-mobile unit that uses beam weapons is (I think?) the Seraphim T2 PD, the simple answer is just to make it stop doing that.

I've not yet found time to investigate it, but in principle we can do a really hilarious thing to fix this properly. The bug, you see, is that when a beam starts with its source under the fog, the beam doesn't render. Making the source visible (for less than one simtick, so it doesn't even appear to the user to ever not be under the fog) causes the beam to appear, but causes a persistent intel blip for buildings.
So: what we could in principle do is, when we detect a beam is hitting a friendly unit, make it turn invisible and spawn a beam from the friendly unit back to the source of the real beam. When we detect that the real (now-invisible) beam has ceased striking this target, we delete the backwards-beam and make the real beam visible again.

It'd be completely ridiculous, but it would probably work. :P

**Comment by aeoncleanse** [comment]
Yeah more work to be done for the statics, but if you can get a PR with the mobile solution, I'm game with it.
