### ISSUE TITLE
Score button shows up when no scores are available

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#304]
This should either be torched, or replaced with an "Exit game" button, which could contain a tooltip that no scores are available (This happens because of lobby options).

**Comment by Sheeo** [comment]
When this is taken a pass at, the interaction between `gameresult.lua` and `score.lua` should be refactored.

**Comment by ggwpez** [comment]
As far is I could reproduce it with this version, the following seems to happen, when a team game is running:

Leave Lame -> No data available								       :  Ok
ACU dead    -> Game Over          -> leave game -> Can see score data      :  Ok
ACU dead    -> leave game          -> Can see score data                              :  Not-Ok

I actually got the Score button right, but the 3. case needs to be handled too, my attempt screwed the score-UI up. You could not see the score, but it was not a pleasure to look at.

**Comment by aeoncleanse** [comment]
Where does this stand. Did it get hotfixed?

**Comment by ggwpez** [comment]
I tired to fix it, by checking the 'gameOver ' Bool in the Victory.lua, and when it's set let the score bee displayed.
That sounds like an easy solution, but somehow I got different values for the Bool. 
The 'aibrain.lua' seems to get the right value for it, but in the 'gameresult.lua' I always got false as value, so I was unable to see when the game was over.
I'm not sure if this is caused by multithreading so the threads hold different values or maybe my development environment was messed up.
Maybe you just also give it a try.

**Comment by Sheeo** [comment]
`ggwpez` those files are executed in different lua states.

The game has three main lua states (execution environments), of which you only really interact with two: the sim, and the UI.

It's a bit inconsistent which files are run where, especially in FAF, but mostly if stuff lives in `/lua/sim` it's only run sim-side.

There should be a synced value available to the UI that says whether scores are available or not, the logic for showing the score button should be something like `scoreOn or gameOver` in the UI.

**Comment by micheljung** [comment]
At least with the current code base, this does not happen because of the lobby options. A full score sync takes place on game end. However if the timing is bad, the sim stops before the scores have been synced -> empty scoreboard.

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/issues/1616
