### ISSUE TITLE
Factory repeat build hotkey doesn't work

### ISSUE THREAD

**Issue by jkstpierre** [FAForever/fa#3164]
Not sure why this is happening, but I've recently noticed that my hotkey for factory repeat build no longer works. No matter what key I bind it to, nothing happens. All of my other hotkeys work fine so its a little odd to me that specifically this single hot key shouldn't work. The only thing I did to modify FA (aside from FAF obviously) is download and run the LOUD mod. But, I've since deleted it and completely reinstalled FAF and FA upon noticing this issue and to no avail. I suspect there's some file that's survived my reinstallations that is causing the issue but I have no idea what it is or where I would find it. Any help would be appreciated!

**Comment by Nojoke185** [comment]
try to delete your game.prefs file at this location:

C:\Users\Yourwindowsusername\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance

(back it up first)

When you next run the game it will be as if you run the game for the 1st time, you will have a new user created and will have default keys etc

This file saves all the key bindings and user settings for the game and persists over re-installations

Other option is to review your current game.prefs and try to find what the problem is with the factory repeat key bind

Hope it helps

**Comment by jkstpierre** [comment]
Thanks so much! It fixed the problem!
