### ISSUE TITLE
Extending LUA / Profiling SupCom

### ISSUE THREAD

**Issue by falk-stefan** [FAForever/fa#3188]
Lately I found some code of an old projects which I abandoned after realizing that what I intended to do was virtually impossible given the short amount of time we spend on this earth.

However, and I can't tell you why, but I checked out the old code and somehow managed to make it work in an afternoon. But let's cut to the chase..

The code uses https://github.com/FAForever/supcom-se which I used as a basis for some code injection. What I managed to do with this is injecting code, load a library and register additional LUA packages. Most of this is possible thanks to the [linker](https://github.com/FAForever/supcom-se/blob/master/scse/scse_lualinker/LuaLinker.cpp) in `supcom-se`.

So, to explaine it in code, we can register a new packages, here called `ai`, and for that register additional functions. We have some C++ lines like this:

```cpp
static int luaAi_helloworld(lua_State *L)
{
    MessageBoxW(NULL, L"Hello World!", L"", MB_OK);
    return 1;
}

static const luaL_reg ai_funcs[] = {
    { "helloworld", luaAi_helloworld },
    { NULL, NULL }
};

void open_ailib(lua_State *L)
{
    LuaLinker::Link();
    luaL_openlib(L, "ai", ai_funcs, 0);
}
```

And now we can use these in any LUA-file of SupCom:

```lua
LOG('Calling ai.helloworld()')
ai.helloworld()
```

Which will open up the message-box for us. Note that this is only possible after injecting very specific (assembly) code into the `ForgedAlliance.exe`-Process after starting it from another `InjectCode.exe`. You can see how the basic idea works here:

https://github.com/FAForever/supcom-se/blob/a402209700294e30b8d9167d141f9fa521c31874/scse/scse_loader/scse_loader.cpp#L174

Now, I am not sure if I remember correctly, but back then some people explained to me that this could be an issue because we'd have to modify a binary file which could be problematic when it comes to distibution. 

However, I still would like to throw this in and ask if somebody has an idea if something like this could be useful in any way.

One thing that comes to my mind would be to run actual compiled code instead of LUA. I don't know if there is a lot that we can optimize with this, and if this idea makes even sense at all (I am counting on somebody who knows a bit more about SupCom than me to speak up) but at least theoretically it could be possible to move (time) expensive funtions out of LUA over to a compiled binary. 

Another thing that might be interesting is just performance-profiling. I don't know if we are able to determine the expensiveness of SupCom's LUA code. I've been looking at [this](http://lua-users.org/wiki/PepperfishProfiler) but. once again. I have too little knowledge about SupCom's LUA to tell whether such a profiler can even work that easily. If not, there could be a way to inject some logic that could potentially open us a door here to get some idea about how fast or slow some implementations are and where it could really pay off to optimize. 

@KionX @FAETHER Can you help here?

**Comment by FAETHER** [comment]
Hello falk-stefan, 
It always amuses me how people come from time to time and try to reverse engineer this mammoth. 
So you could try and optimize lua code this way by writing very good assembly and calling things from lua this way. I think it will be faster because you can offload a lot of time from interpreter, but the question is what exactly you want to replace. There isn't actually a one single place in this game where you can just stick this in and get a notable performance increase, the issue is much wider. It's not that there is one definitive bottleneck, it's more like million different places chip in a little bit on performance and general programmer's negligence adds up to create the problem this game has. Back to the topic, you also have to consider that calling stuff from lua still has an overhead. But honestly if I were to say my opinion, doing all this is just diminishing returns. It's actually better to use this to improve the game, add features, fix bugs. But we do that statically now, that repository has unnecessary overhead of runtime patching which is bug prone/hard to debug. There isn't much I can help you with the engine internals, because as of right now it really comes down to you just spending godly amount of time doing reverse yourself if you want to get anything done. I see the prospect of rewriting the engine to be better, since all shaders are opensource so you can implement all the effects this game has in theory. You just have to have a deep understanding of graphics api, and what shaders actually do. I am saying this because generally, graphics are the most expensive to implement in most games, and not every game has an advantage of these things lying on the open. As graphics is the hardest thing to recreate. Anything else is pretty much plug and play with libraries that exist today.

**Comment by KionX** [comment]
I agree with FAETHER. I will add that the shaders here are also hopelessly outdated)
We need people who will fix the leaky engine or rewrite it.

**Comment by falk-stefan** [comment]
@FAETHER 

>It always amuses me how people come from time to time and try to reverse engineer this mammoth.

And it's not even my first time thinking of doing so :D 

> There isn't actually a one single place in this game where you can just stick this in and get a notable performance increase, the issue is much wider. It's not that there is one definitive bottleneck, it's more like million different places chip in a little bit on performance and general programmer's negligence adds up to create the problem this game has. 

Please correct me here if I am wrong, but as far as I've been told, the biggest issue SupCom has is the fact that simulations run basically single-threaded? And, if I'm not mistaken here, the LUA code in particular runs essentially only on one single thread?

If that is right, my train of thought here is to try optimize what we can to reduce load on that single thread. As you mentioned, there is probably no place where we can just change a few lines of code and the game runs faster. 

That last point I am making, and maybe I should have put that first, is, that there _should_ be a way to profile the LUA code.

I looked at [Profiling Lua Code](http://lua-users.org/wiki/ProfilingLuaCode) but I know too little about SC-LUA to be able to tell if this can actually be done. Using `debug.sethook()` seems like something one could use here but the question is whether this can work sort of "globall" in order to capture all method calls s.t. we can create a calling-tree like so:

![image](https://user-images.githubusercontent.com/58136779/97775084-f0281800-1b5d-11eb-924a-4deeee4d0640.png)

And _if_ this is not possible in SC-LUA, then there _might_ be a way to do this by hijacking [one ot those known methods](https://github.com/FAForever/supcom-se/blob/master/scse/scse_lualinker/LuaLinker.cpp) in order to measure execution-times. 

This way I am sure we could idendity slow SC-LUA code that way and then decide what to optimize.

---- 

Moving SC-LUA code to C++ might be much harder to do. I think this could probably only be used for very expensive mathematical operations which get called very often or something like that. Maybe that's only an option in rare cases. After all, we don't really know that's why profiling the SC-LUA code would have to come first anyway.

@KionX If Unity had a Lockstep-Implementation for RTS-like games I'd say: Let's get together and rebuild SC:FA 😆

**Comment by KionX** [comment]
There is this(not tried):
https://github.com/FAForever/fa_profiler

Incomplete implementation of LUAJIT:
https://github.com/Eximius/FA-Extension/tree/odd-develop

Current exe patches:
https://github.com/FAForever/FA_Patcher
https://github.com/FAForever/FA-Binary-Patches

**Comment by falk-stefan** [comment]
@KionX The first one looks like what I had in mind. The question is whether it's working. @Eximius can tell?

**Comment by KionX** [comment]
I don't know. He left the FA long ago.

**Comment by KionX** [comment]
I wrote a profiler for FAF as a mod.
[FAFProfiler.zip](https://github.com/FAForever/fa/files/5933567/FAFProfiler.zip)

**Comment by Eximius** [comment]
> @KionX The first one looks like what I had in mind. The question is whether it's working. @Eximius can tell?

It was working a long time ago. It would literally output the profiler data through the socket to a file for opening with android profiler dump tool. Was kinda cool.

However, seems like we did not describe anywhere that it needed a special receiver for the gpg net socket (Needs FOpen, FWrite, FClose "gpg net commands" ) (FA-Extension is used).

**Comment by MrRowey** [comment]
@Garanas this still needed as i know you have a profiler now

**Comment by Garanas** [comment]
We literally use `debug.sethook()` for the profiler 😄 .
