### ISSUE TITLE
Suggestion: Remove Supportive Factories & Increase High Tier Unit Capability

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3250]
Hello, guys!

I would like to propose the removal of supportive factories, making the hq-factories more productive and higher tier units more resistant to lower tier units spam, making the feel of progress more prominent. Here are my reasons:

####  Strategy

The producing entities always had a value in real life warfare and their location was a big part of a strategy. Currently, this strategical opportunity is diminished by cheap and spammy factories.

####  Experience

Currently, the game heavily relies on spam, especially on enormous t1 spam. This is highly encouraged by current balance where higher tier units are easily outspammed by t1 units. There is a direction to make tiers much more distinctive, but spammy factories work against it as well.

#### Progress

There should be a value in progress and high tier units should be more capable, as well as high tier factories should become more of an achievement, should become more productive and perceived as a strategical asset.

#### Base Building

Less factories will allow for more compact and more thoughtful bases.

#### Spam

Higher tier units can be outspammed by low tier units, thus reducing strategical variety and making every game repetitive.

#### Progress

This diminishes the feel of progress, disabling the "tall" play-style.

#### Factories

Factories should become more productive, thus removing the need for assisting (the main reason for adding supportive factories). I would suggest threefold increase in tier productivity. Should you need t1 spam, just upgrade your factory.
factory t1 : 20 -> 40
factory t2 : 40 -> 120
factory t3 : 90 -> 360

#### Unit Capability

Higher tier units should be more capable against lower tier units spam. I would suggest the coefficient of 5 - the next tier should be at least 5 times more capable.

For example, let's explore the Seraphim land tank hull | dps (land):
t1 : 280 | 24
t2 : 1350 | 60  = 4.8 | 2.5 times better than t1 ~ 3.65 times better in average
t3 : 4700 | 450  = 3.5 | 7.5 times better than t2 ~ 5.5 times better in average
Ythotha 67000 | 3800 = 14.2 | 8.4 times better than t3  ~ 11.3 times better in average (just for reference)

So we see, that t2 unit is lacking in average capability. The coefficient is discussable of course. The main goal is to make spam less viable. May be 6 is better.

I would suggest the 2-fold increase in production speed. We could make higher tier units about 2 times longer to build (as higher tier units will be more robust, so less spammy):
t1 : 270/20 = 13.5 sec to produce in t1 factory -> 270/40 = 6.75
t2 : 990/40 = 25 sec to produce in t2 factory ->1500/120 = 12.5
t3 : 3600/90 = 40 sec to produce in t3 factory ->7200/360 = 20 -> 8640/360 = 24

## Conclusion

These changes will obsolete factory spam and make them valuable strategical asset. Low tier unit spam will become less viable, thus promoting more variable strategies. The feel of progress will be refreshed with higher tiers being more significant.

All the best :D

**Comment by Sprouto** [comment]
This seems really to be two subjects in one.

The factory output is one I entirely agree with - and the logic is completely sound.   This change is demonstrated in The LOUD project, where factories have build power similar to what you have suggested here.   This not only reduces the spam of factories, but engineer spam as well - since the relationship of build power between factories and engineers is addressed, making the construction of another factory more attractive than the equivalent number of engineers.

The relationship between unit tiers is a second subject entirely - and requires a more detailed analysis than provided here.   Higher tier units should represent a greater concentration of firepower than T1 units - but you need to be careful with the tipping point, since at some point T2 units will be so much more attractive that T1 units will have no value at all once T2 arrives.   This same consideration occurs between T2 and T3 - and T3 and T4 (Experimental).

**Comment by MerryPanda** [comment]
> 
> 
> This seems really to be two subjects in one.
> 
> The factory output is one I entirely agree with - and the logic is completely sound. This change is demonstrated in The LOUD project, where factories have build power similar to what you have suggested here. This not only reduces the spam of factories, but engineer spam as well - since the relationship of build power between factories and engineers is addressed, making the construction of another factory more attractive than the equivalent number of engineers.
> 
> The relationship between unit tiers is a second subject entirely - and requires a more detailed analysis than provided here. Higher tier units should represent a greater concentration of firepower than T1 units - but you need to be careful with the tipping point, since at some point T2 units will be so much more attractive that T1 units will have no value at all once T2 arrives. This same consideration occurs between T2 and T3 - and T3 and T4 (Experimental).

Oh, sounds very interesting!

And how have you divided unit tiers in your mod? :)

**Comment by Sprouto** [comment]
By analyzing the data from ALL tiers and ALL classes, we were able to see a lot of distribution anomalies and make informed choices about the relationship of units not just to others of the same type, but across the tiers, and more importantly, across classes.   The most obvious was that of air units in general, having more firepower (and of course mobility), for a far lower investment.

The long and short of the topic is that without drastic changes, we were able to narrow the gaps between the tiers so that the transitions are more natural, and the value investments across all units fall within reasonable ranges - regardless of tier.    This kind of framework allows you to take any unit, and evaluate their performance, and their costs, in relative terms - thus arriving either at a suitable cost adjustment or a change in stats, or both, while retaining the original purpose and effectiveness of a unit.

**Comment by Benzi-Junior** [comment]
For the factory discussion I refer to:
https://wiki.faforever.com/index.php?title=Game_Modifications_(Mods)
The engy mod is there more for performance reasons than balance.
And when do you see mass support factories on anyone other than air 

As for the tier progression you talk about I'm not exactly sure what you are talking about, sure there is T1 spam lingering around more and more in games but have you seen what a single titan does to the equivalent mass in spam ?
I mean that's less than 20 strikers, I'm not sure they even get in attack range of the titan, even if he is left just standing there.

Your suggestion seems to be that it should be higher tier > lower tier but that removes almost all strategic consideration for how units match up + it makes any strategy that isn't a tech rush useless.
Just look at the state of Air, games end because one team's air player is a minute faster to t3 because once t3 shows up nothing else matters.
This would also mean that since when T3 shows up, you only have to counter T3 and experimentals, in other words: "All hail king Percival"

The three theaters of war in FAF each have their own approach to tech progression, 
Airforce: Make a token ammount of AA to prevent your allies getting sniped, eco and tech up as fast as possible, once you get yor first ASF out, halt all other production and never look back, this is your life now, 
Land : Spam T1, Tech up whenever your opponent relents their assault, slowly phase out your lower tier production in favour of stronger, more efficient T3 units.
Navy: Build frigates, and then, don't stop building frigates,  tech up when you can do so without slowing your frigate production, don't go T3 unless you have a clear advantage, once you hit T3, keep making frigates.

I personally like the navy setup, t1 units never loose their usefulness, but there is so much strategy built into the t2 stage, it doesn't just steamroll t1 units, they have to make use of their specific  advantages.
Air needs a change, although possibly just by making AA turrets better, since they have a clear progression and are all but useless if they are a tech level behind.
Land is a healthy mixture of the two, with superior economy you absolutely can keep the bulk of your army T1 thtrougout,  make no mistake it is a disadvantage,  but it's a APM vs Efficency tradeoff

**Comment by MrRowey** [comment]
@Tagada14 could be closes as I don't see us reverting the Engy mod and removing the hq and support factory's
