### ISSUE TITLE
mod_info.lua change to 'requires'

### ISSUE THREAD

**Issue by muchstuffmuchstuff** [FAForever/fa#3255]
For ease of use for new players, which I assume FAF wants to attract and maintain as per the latest poll, the Requires section when we upload our AI's should be changed to name, not UUID. Below is the current code.  But since UUID's change, but names don't, we'd always have to counter-upload each time Uveso updates his own, clogging the vault needlessly with uploads just to adjust our own requires UUID number. This would help new players and increase their playing experience. Below is the current code, which requires the UUID # not a name.

  if not IsHost and dependencies.requires then
                    for innerUid in dependencies.requires do
                        if not mods.selectable[innerUid].ui_only and not mods.sim.active[innerUid] then
                            mod.sort = 'X'
                            mod.type = 'NO_DEPENDENCY'
                            mods.missingDependencies[uid] = mod
                            break
                        end
                    end
                end

**Comment by Garanas** [comment]
To clarify further: the 'requires' variable defined in the _info.lua file requires UUIDs. A UUID is bound to a version in the vault. Therefore if the underlying mod receives a vault update, the uuid is changed. I'm not entirely sure if the correct uuid (version) of a mod is downloaded from the vault when you join the game - or just the most recent. In either case, its a bit of a hassle especially if it only downloads the most recent.

Either how - it would be nice to:
 - have it set to the name of a mod, instead of its uuid.
 - have an additional field ('requiresWeak') that allows you to match on the name of a mod, instead of an uuid.
 
 The first option would break backwards compatibility, the second one would be a faf-speciality that would greatly benefit the ai devs and people that are not too aware of the fact that uveso is required for practically all ai mods.

**Comment by Uveso** [comment]
We need a check wit UID not with name.

As example, when a mod needs the Uveso AI as required mod.
Then it will need a special version number where all hook and function names are matching.

Last update i changed some function arguments that needs to be patched in other AI mods.
Now, if you only check the Mod name and not the Mod UID then you can't check for the right version you need.

This will lead in mod compatibility versions missmatching and many errors. 
(this is the reason why we never changed it from UID to name based check)
