### ISSUE TITLE
Kyro's Lobby Mod maybe should be Integrated into FAF officially

### ISSUE THREAD

**Issue by Azraeel** [FAForever/fa#3390]
This is a request by players just decided to make the issue, it seems to have a lot of nice features although haven't taken a look at it from a code perspective. 

https://groups.google.com/g/kyros-lobby

Just something to be noted i guess :)

**Comment by Garanas** [comment]
Where do I actually get the lua files?

**Comment by Azraeel** [comment]
> 
> 
> Where do I actually get the lua files? edit: found it

also doesnt seem to work in FAF Develop Branch rn works in normal

**Comment by macdeffy** [comment]
I have made a number of changes to kyro's that fixes UI scaling and sorting issues that would crash lobby on some maps, as well as add some extra buttons for switching full share/fixed and optimal on the fly. I was trying to add ability to manually line move slots, since it doesn't line up teams properly on all maps, but that has proven difficult for me. I was mostly messing with it for my own amusement.

https://drive.google.com/file/d/1iLzboy6N6AHiSoTA-EEHi2ZWosSu2OsF/view?usp=sharing

here is a zip of it with those basic changes. My other version with manual sorting is too bugged to be worth using, and i could  provide  it but it's likely too messy to bother with. My goal was if I could get it where you can line up the slots for maps that don't mirror correctly, then even an auto sort button would be possible, but am not a programmer so likely beyond what i could figure out anyway.

**Comment by Garanas** [comment]
I'll be honest that this is not high on my priority list at the moment. The amount of unknown code that this introduces is huge - it would require quite some time to not just get into the code, but also to properly test everything.

I'll be closing this issue next Monday, unless someone else is interested in picking this up in the near future.

**Comment by macdeffy** [comment]
fair enough. for what's it worth, i've been using what I have for a year without issue, but it's easy enough for people to just manually add this on their own, so not really necessary to integrate.

**Comment by Garanas** [comment]
I suggest someone makes a forum post about this instead of integrating it for now. We could also put it in the news to give it some attention. Integrating it is (too) much work (for now). 

As @macdeffy points out, replacing the lobby yourself isn't too difficult. I am closing this issue.
