### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by NoobDragoon** [FAForever/fa#3465]
Unhandled exception notification then game crashed attaching log files and notepad file  to the deves to look at.
[game_15439354.log](https://github.com/FAForever/fa/files/7272418/game_15439354.log)
[FAF Game Crash.txt](https://github.com/FAForever/fa/files/7272419/FAF.Game.Crash.txt)

**Comment by Garanas** [comment]
I've run the replay and it produces this:

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0050dfd8
    attempted to read memory at 0x0000005c

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /showlog /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_15439354.log /replay C:\ProgramData\FAForever\cache\temp.scfareplay /replayid 15439354

Callstack:
	Unknown symbol (address 0x0050dfd8)
	Unknown symbol (address 0x0068af40)
	Unknown symbol (address 0x3a20736f)
	Unknown symbol (address 0x3a20736f)
```

The information is part of the debugger - it is a separate application that is started by the game when it hard-crashes. 

![image](https://user-images.githubusercontent.com/15778155/135746660-4c1b83fb-8c2e-4035-9828-174ef38b3424.png)

This is fixed with https://github.com/FAForever/fa/pull/3449 and is available in FAF Develop. Tomorrow it will be merged into the regular branch with the patch. Until then I can only recommend you to play / host on FAF Develop instead.
