### ISSUE TITLE
Cheat menu Inconsitance Unit Placement

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#3655]
As I Spoke with Jip When I was Spawning in the unit while holding Shift to spawn a Copy of the unit elsewhere it has a weird interaction of skipping unit for spawning them nowhere near where I click originally as you can see here in this [video](https://www.youtube.com/watch?t=56&v=CpqcRlpJVfk&feature=youtu.be)

Or you can see here in this [replay ](https://replay.faforever.com/16250486) where I'm spawning in stuff as a test I was performing on checking ACU OC Damage

**Comment by Garanas** [comment]
Managed to reproduce it:

![image](https://user-images.githubusercontent.com/15778155/152134794-72379926-fa4c-4f1d-8d4b-fdfe4f9ba39f.png)

The logs show when a command was issued (because of the build preview) and when the callback was called (to make the unit).  Note that two commands are issued, one with the unit and one that is empty. I'm not sure why the latter is empty. Regardless - after those two commands a unit should be made. And that doesn't always happen.
