### ISSUE TITLE
bring back rank update notifications

### ISSUE THREAD

**Issue by jnorthrup** [FAForever/fa#375]
balancing a match is certainly easier with "00" at the end of ranks however i think the knee-jerk action taken last year to all but remove access to rank and recieve specific updates about rank changes was pretty awful.  presumably the rank notifications can be turned back on if this can be put to a vote.  I doubt the action to obscure was the result of any consensus.

**Comment by ChrisKitching** [comment]
I agree: rounding the numbers to the nearest 100 removes a significant amount of information. You "jump" abruptly between two rather distant rating values in ways that can meaningfully affect your gameplay experience (you end up in games you're slightly ill-prepared for while you're an X51, for example).

I think we should revert last year's pretty arbitrary change. It certainly warrants an actual discussion instead of the rather hasty action it incurred last time. If nothing else, we should just divide rank values by 100: having two extra zeros in the UI is a waste of space.

**Comment by jnorthrup** [comment]
so-called "rank-bashing" didn't end but it sure it sure pulled the wool over my eyes just when my game started improving and I could relate my actions to end-of-game rank results.  the same 5 1500 players didnt stop joining the 800 matches.

**Comment by aeoncleanse** [comment]
If you're talking about the end-of-game chat message saying how much rating you've gained/lost, that needs to stay hidden. All it did was cause unnecessary bitching because people thought it was a ladder. It is not, it's just a way to match players up. The only way to increase it is to improve as a player faster than the average rate of player improvement.

You can see anyone's exact rating and deviation by checking their details in chat, I think that's enough.

**Comment by jnorthrup** [comment]
i disagree, the graph ui is suck.  acessing it and navigating around the bugs is a pita.  having a note that tells you what you got for playing a few hundred above or below the other team is helpful and valueable, or at worst case a log.  that's not available and FA is not a every-kid-gets-trophy sport, improving the chat features would be better served than presenting us with a vague rank and hiding the actuals.

**Comment by Sheeo** [comment]
Closing this because it's in the wrong repo, there were never rating change notifications in the FA code.

Use FAForever/lobby.
