### ISSUE TITLE
Minimap always renders health bars

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3828]
It shouldn't...
![ForgedAlliance_2022-04-27_18-28-16](https://user-images.githubusercontent.com/10947024/165567511-cfa124b0-63c8-476a-b2f6-bc421d9f8ce3.png)

**Comment by Garanas** [comment]
@Strogoo ?

**Comment by Strogoo** [comment]
Yeah, using `cam_DefaultMiniLOD 0` here was not a good idea.
https://github.com/FAForever/fa/pull/3667/files#diff-4970a1162298ae0f7e20b52a3cc5796fb5f5f0b31253fb196ccced1caca00983R185

As you remember lower LOD value means better graphic. So with `0` it renders everything. I thought it wouldn't be a problem as I disable meshes rendering completely when it's 0, but I forgot about all other stuff like health bars that also uses it.

Also why I missed it during testing, is because `DefaultMiniLOD` is used when new istance of minimap is created. As you can see in my PR, I putted this command in the end of CreateMinimap() function, so in normal situation when you have minimap enabled by default, it creates the minimap first with normal default LOD value and only then execute this command with 0 (this will only affect the next instance of minimap that in normal situation shouldn't even be created at all)

**Comment by Strogoo** [comment]
Just did some testing, even if minimap is disabled by default and you want to open it during the game, it still works just fine because it goes same way: CreateMinimap() -> cam_DefaultMiniLOD 0 in the end -> next minimap will be broken (but it won't be created anyway, even if you close current minimap and then open a new one, the instance will be the same, as it just use hide/show instead of destroy/create).

The only situation when it fails is when you launch the game with minimap, then restart simulation via game menu (menu->restart game), then it creates a new minimap after restart, but the `DefaultMiniLOD` vaule is already changed during first launch, so new minimap will use this `0` vaule and will render everyting.

Well, not super critical I would say, but I should definitely fix it in next game patch
The only situation when it fails is when you launch the game with minimap, then restart simulation via game menu (menu->restart game), then it creates a new minimap after restart, but the `DefaultMiniLOD` vaule is already changed during first launch, so new minimap will use this `0` vaule and will render everyting.

Well, not super critical I would say, but I should definitely fix it in next game patch

**Comment by Garanas** [comment]
Fixed with 3636.
