### ISSUE TITLE
Having the auto-balanced-teams function connected to "Spawns = random" is confusing

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#415]
This oddity is quite confusing, and has spawned at least one complaint:
http://forums.faforever.com/forums/viewtopic.php?f=40&t=9303

We should definitely, at the very least, name the option something sensible.

While we're at it we probably want to make it stop trying to solve an optimisation problem via a random traversal of the search space :/

**Comment by Crotalus** [comment]
Yes, and maybe introduce "Autobalance spot" / "Autobalance team" so you can have balanced spots as well. The hard thing I guess is to determine what's the opposite spot is in all maps.

As to the random search it's just for randomization of the algorithm, otherwise you will get identical teams if same players play another game.  With the latest change there's a chance to pick a random one iff that composition is at least 95% of the balance of the best one found.

**Comment by ChrisKitching** [comment]
More confusion:
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9335

**Comment by aeoncleanse** [comment]
System in 2017 is much more understandable
