### ISSUE TITLE
Cannot start sim in develop-branch

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#418]
Anyone else having trouble launching from the current develop branch? I've seem to be having this problem for a while:

debug: Loading module '\000/lua/sim/engineermanager.lua\000'
debug: Loading module '\000/lua/sim/strategymanager.lua\000'
debug: Loading module '\000/lua/sim/strategybuilder.lua\000'
debug: Loading module '\000/lua/simutils.lua\000'
debug: Loading module '\000/lua/simplayerquery.lua\000'
debug: Loading module '\000/lua/aipersonality.lua\000'
info: Sim::Create() crashed: attempt to get as string a number value
      stack traceback:

I'll try go back in git commit history and see where it started to happen

**Comment by Crotalus** [comment]
Seems like this commit breaks it for me:

7e9961314560c9570e71653963c671c6957d019d

**Comment by Crotalus** [comment]
Resetting my prefs solved it, maybe some casing of keys messing it up? @ChrisKitching

**Comment by ChrisKitching** [comment]
Known problem from a while ago. You can only encounter this if you happened to run the lobby on develop while it was broken. Now it's fixed, it won't ever break your preferences file in this way again, but it won't fix it.
Since we never released the preferences-file-breaking code, this is fine: just clear your preferences and move on.
