### ISSUE TITLE
Alt-related shortcut produces OS beep sound in windowed mode

### ISSUE THREAD

**Issue by timocov** [FAForever/fa#4239]
**Describe the bug**

If you run a game in windowed mode then any (almost?) hotkey with Alt, e.g. Alt+S or Alt+E would produce a beep system sound. If you switch to fullscreen mode then it works fine.

Not sure if it is possible to fix though (let me know please).

**To Reproduce**

Run a lobby or a game in windowed mode and press Alt+S. It happens even if you have an action assigned to this hotkey - action is applied and the sound is produced.

**Expected behavior**

No sound is produced like it is in fullscreen mode.

**Screenshots**

N/A

**Additional context**

Let me know if it unclear or cannot be reproduced on your side and what I can provide additionally.

**Comment by Garanas** [comment]
What operation system are you running?

**Comment by timocov** [comment]
Windows 10 x64

**Comment by Garanas** [comment]
Ah, yes. I can hear it too. Not sure what the solution is yet.

**Comment by haifron** [comment]
I found this issue a while ago too, there's a way to turn it off:
https://community.adobe.com/t5/premiere-pro-discussions/using-alt-key-modifier-on-win10-causes-os-sound/m-p/9034759
You want to go to Control Panel > Sound > Sounds (or just run "control.exe mmsys.cpl,,2" in cmd). Find "Default Beep" in 'Program Events' and set it to "(None)".
If you don't want to change your default sound scheme then you can make one specifically for FAF & switch back and forth whenever you play, just click "save as".

From what I gather it's essentially caused by the program not telling windows it's using that key combination so windows thinks you're trying to use an OS shortcut, and is telling you "hey that combination doesn't do anything". I don't know if that's something people could change, but when you can just turn it off I don't know if there's much point trying.

**Comment by Garanas** [comment]
We can not change that from within the game, the solution you provide is likely the best one we have. Thank you for coming forth with it
