### ISSUE TITLE
Absolver: shield disruptor suggested changes

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4400]
**Describe the feature**
Reshapes the Absolver into the T2 phase where it would be much more useful in the game as shields start at the T2 phase.

**Expected behavior**
Make it seen more often in game, as I have not seen one in (A)eons.

**Suggested stat changes**
Tech 2 unit
Reverse : 1
Range: 0-55
Damage: 20
DamageToShields: 800 (DPS 400)
Mass: 250
Energy: 1500
Health: 500

**Comment by Prohibitoram** [comment]
Pretty cool idea.

**Comment by Tagada14** [comment]
Aeon already has a very strong T2 Land Roster with quite a few different tools, I see no reason to buff it further. Absolvers are extremely useful units that are criminally underused and IMO they are in a good spot right now.

**Comment by EvildrewFAF** [comment]
> 

They are too expensive given you have to go T3 land first then sacrifice not making T3 bots. The T2 roaster is not very strong, Aoen and Seraphim have no comparable units to sparkies, beetles, hoplites, mongoose. 
All you are doing is making claims and blanket statements without providing any evidence or argumentation to back them up. Your opinion is not enough. Please post some replay Ids where you or someone else used absolvers and they were game changing or decisive.

**Comment by Tagada14** [comment]
I don't need to go replay hunting to prove my point to you. It was discussed with the rest of the Balance Team and we agreed that Absolvers are in a fine spot. If you play against a faction that has mobile shields then Absolvers work very well and are worth making instead of 1-2 extra snipers. They are also very strong support units in breaking fire bases.
If you think that Aeon T2 land isn't strong then you might have been living under a rock for the past year.
