### ISSUE TITLE
Is this real, can we use it?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#450]
http://forums.faforever.com/forums/viewtopic.php?f=2&t=8501&start=10#p83857

**Comment by Crotalus** [comment]
The first trick would make it harder to regret an action in the UI, when for instance you decide to upgrade something but then comes to another conclusion and release the button with the cursor outside the actual icon. 

The second improvement is already there, caching of textures.

**Comment by Crotalus** [comment]
An idea for reducing queue lag (where it's most obvious) is to make it work on a UI version of the queue and syncing it to the sim in the background. It's deleting / re-issuing alot of orders anyway when you drag them around.

**Comment by aeoncleanse** [comment]
OK, let's not do this then. Hide/Destroy can be looked at though...

**Comment by Crotalus** [comment]
Seems like Enable / Hide is already used somewhat. The construction tabs seems to be re-created though

**Comment by ChrisKitching** [comment]
I don't think changing the semantics of buttons to be "fire on down" is a sensible idea.

> The map preview / resource markers is an example of that.

Object pooling needs to be used with care: I used it in that case because measurements supported the move. Excessive use of object pooling can be a performance bottleneck itself. It just so happens that the map previews need to spawn zillions of stupid mass extractor icons, and saving the overheads of having to recreate them every time we switch map was pintful.

> I've also thought a bit about the whole UI, what would happen if we actually Hide() stuff instead of create / destroy it all the time?

Again: good idea, care needed. You have to be finnicky about lifecycles if you do this, so for some things (such as popup dialogs in the lobby) it's not worth it (you may have noticed my U-turn on that front).
I've not looked at the in-game stuff, but there's liable to be some opportunities there.

> As a final note we should probably get rid of the whole "layout" system

The what?


Another general note: Use closures. Closures are your friend. I noticed (in my extraordinarily fleeting glance) that construction.lua seems to use one giant function for handling click events. You'll get better performance using closures per-button.

In case unfamiliar, a closure is effectively a function with some values "substituted in". The values that can be "substituted in" (instead of being read at the time the function is executed) are local variables available in the scope that declares the function.
So, in general, try and capture the references that a button will need and copy them into the closure when you make the listener, instead of forcing the listener to go do table lookups to find things. Definitely don't pour a ton of buttons into one big function and have it sort out the mess.

**Comment by Sheeo** [comment]
OP has been answered here, I believe.
