### ISSUE TITLE
NavMesh bug - inconsistent GetLabel result for unpathable locations

### ISSUE THREAD

**Issue by maudlin27** [FAForever/fa#4687]
On Pelagial, the Nav generator returns a location as pathable for 'Land', but impathable for 'Amphibious' (it should return impathable either way) - since amphibious units can go anywhere that a land unit can, I wouldn't expect any cases where an amphibious unit can't path somewhere, but a land unit can.

The three locations in blue in this screenshot are examples of locations on Pelagial where NavUtils.GetLabel('Land'...) returns a non-nil value, but NavUtils.GetLabel('Amphibious'...) returns nil.
https://cdn.discordapp.com/attachments/941273132818391100/1074376024751612034/image.png

Enabling the UI for the NavMesh, it indicates that these locations should be returning nil in all cases:
https://cdn.discordapp.com/attachments/941273132818391100/1074376235330850856/image.png
https://cdn.discordapp.com/attachments/941273132818391100/1074376322526220369/image.png

The code I used to draw the blue boxes in the first screenshot above triggers whenever the NavUtils returns a non-nil value for land pathing but nil for amphibious pathing (the log itself is the following lines - more for reference so you can see Im using the same position for NavUtils 
LOG(sFunctionRef..': Base position='..repru(tBasePosition)..'; Land nav='..(NavUtils.GetLabel(refPathingTypeLand, tBasePosition) or 'nil')..'; Plateau nav='..(NavUtils.GetLabel(refPathingTypeAmphibious, tBasePosition) or 'nil'))
                        M28Utilities.DrawLocation(tBasePosition)

One way of reproducing is to cycle through every location on the map in 1x1 increments, and check if NavUtils.GetLabel returns nil for amphibious and not nil for land.

**Comment by Garanas** [comment]
The problem is how we 'alleviated' the navigational grid being coarse, see also:

- https://github.com/FAForever/fa/pull/4555/files#diff-54afb8d1e2391054af22d032f5ee6fad652b7a99d5ec28ff484a907efbd0f74eR67

Where we try to find the nearest valid leaf. In this specific location the amph and land grids both have one valid neighbor:

![image](https://user-images.githubusercontent.com/15778155/222362940-c26e3cd6-fead-47d1-a5d8-f1799d597a70.png)

![image](https://user-images.githubusercontent.com/15778155/222363021-81a41701-bbf9-4dd9-ac16-3e6d46a7b864.png)

I'll add a condition to the function such that the distance travelled to get to the nearest valid leaf should not be larger than the size of the leaf we found. That should alleviate some of the issues you describe here
