### ISSUE TITLE
Reimplement Missing AA Models On Atlantis

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#4760]
**Describe the feature**
Reimplement the Flayers and Flak 'structures' back into the UEF T4 Atlantis model.

---

**Expected behavior**
Flayers and Flak deploy and fire to match with Atlantis anti-air fire animation(s).

---

**Screenshots**
![image](https://user-images.githubusercontent.com/121060254/222238996-09b69e4f-91b2-4c7b-a026-b0ea6e8c7e43.png)
![image](https://user-images.githubusercontent.com/121060254/222239036-36d38fa4-4159-45e9-8932-a09c34f46990.png)

---

**Additional context**
These mini-Flayers and Flak could be seen in the gameplay trailer for Supreme Commander.
_Link to the trailer on YouTube: https://www.youtube.com/watch?v=YTEK91uEvPo&t=99s
Timestamp: 1:35 (Atlantis surfaces, doors open, Flayers pop out and proceed to engage aircraft.)_

For whatever reason, they were removed when the game was released which carried over to current-day FAF.
As shown below:
![image](https://user-images.githubusercontent.com/121060254/222239720-2d977eb7-0652-4244-8560-5743a49a358e.png)

**Comment by EvildrewFAF** [comment]
There was also a Flak on the rear end of it. There is a version of this working +/-ok in on of the mods that is out there, Future Battle Fields I think it is called...
But the optics of the Atlantis in that mod was changed noticeably and there is a copy right in the mod, so don't think you can just steal it.
My assumption though is that the Sams and the Flak are there but just hidden since they probably were not working correctly and no one could figure it out at the time, so should be a doable task.
https://www.moddb.com/mods/fbp-future-battlefield-pack/images/uef-atlantis-model-improvements1

**Comment by MadMaxFAF** [comment]
i'll add this to my list of things to do, not sure about adding the flak as that would be an extra weapon and would need balance team approval

**Comment by MadMaxFAF** [comment]
the models don't exist on the atlantis but they are in separate units ues0402 - ues0404
![image](https://github.com/FAForever/fa/assets/62246181/696883bd-1119-4fb9-a90a-905ec277b129)

**Comment by MrRowey** [comment]
Just Keep it to having SAMS as no other Aircraft Carrier has flack on them
