### ISSUE TITLE
Base game AI takes into account the Cybran build drones

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#4844]
**Describe the bug**

The AI is trying to use Cybran build drones in formations:

`WARNING: *FORMATION DEBUG: Unit ura0001o was excluded from the formation because its layer could not be determined` 

These are units, but their entire purpose is to be part of the build animation.

**To Reproduce**

Run the game with a few AIs like this:

![image](https://user-images.githubusercontent.com/15778155/228055446-52278d4b-d304-4992-8cec-54f10989b161.png)

The errors will pop up soon enough!

**Comment by relent0r** [comment]
I 'think' this is being caused by the platoon template called `T123EngineerBuilder`, which I created so its my bad. 
It performs the following category check. 
categories.ENGINEER - categories.ENGINEERSTATION - categories.COMMAND

This would allow the inclusion of that drone. Easy enough to fix. I'll take a look tonight.

**Comment by relent0r** [comment]
ok this didn't come from where I thought it did. I'll have to do some more logging to see what platoon builder is generating this.
