### ISSUE TITLE
Balance idea: Sub HP Buff

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4978]
## Intended changes

Tech 1 Sub
```
HP increased by 100
```

## Thoughts on the changes

Allows subs to take 2 hits from torp bombers. Does not apply to sera, but they have anti torp which will accomplish the same result.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Basilisk3** [comment]
Torp defence cannot intercept depth charges, so the Searphim sub would still get one-shot with the torpedo bombers that use depth charges. It also has problems defending against the torpedo bombers that use regular torpedoes, because they are usually dropped very close to the sub. So with this change, every submarine will survive one pass, except for the Seraphim one.

**Comment by Basilisk3** [comment]
Oh, I just saw the other Issue. Ignore this then, just keep in mind, that some torpedo bombers are already blocked by anti-torpedo weapons.

**Comment by Spikey84** [comment]
@Basilisk3 I think @Garanas has a solution for the torps dropping in the incorrect area. Once he is done with the PR we can test and make sure it functions as intended.

**Comment by Garanas** [comment]
See also: https://github.com/FAForever/fa/pull/5000
