### ISSUE TITLE
UEF commander Billy nuke explosion animation is too dramatic

### ISSUE THREAD

**Issue by adubaisi** [FAForever/fa#513]
The UEF ACU billy nuke explosion animation is disproportional with its damage. I propose to use the explosion animation of the Support Commander (SCU) as a replacement.

**Comment by aeoncleanse** [comment]
Tried it out, it looks terrible when scaled to Billy's explosion size.Close plz

**Comment by Sheeo** [comment]
Could we have some video footage of the changes in unit action?

**Comment by aeoncleanse** [comment]
If I can get XSplit working, sure.

**Comment by ChrisKitching** [comment]
You could also give us a patch we can easily pull down and test out

**Comment by adubaisi** [comment]
I didn't say anything about resizing. The Billy's major damage radius hardly worth bigger explosion than the SCU's. I meant to use the SCU's explosion as it is without any resizing. If someone don't like that, he can create a custom explosion (e.g. RK's explosions) for it. Again, my main contention is that the explosion is disproportionate with the actual damage.

**Comment by aeoncleanse** [comment]
So change the damage, not the blast. The blast is there to show people how big the damage radius is. Firstly, the Billy damage inner is half as big again as the SCU blast, and secondly the outer radius is a massive 15 units larger!

IMO part of balancing Billy should be increasing the damage of the outer radius anyway, it IS useless right now. Once that happens, it will be deserving of the full nuclear boom.

Check out #596 if you want to see how it looks scaled, because there's no way in hell we're giving it the unscaled explosion.

**Comment by adubaisi** [comment]
Changing damage is a balance issue as you noted. There is a team assigned to look at balance issues. Balance changes are not bugs to be reported here by anybody.

**Comment by aeoncleanse** [comment]
This issue isn't a bug report, it's an opinion based on a balance phenomenon...

**Comment by Sheeo** [comment]
It's a fair opinion.

I think some of the explosions are a bit overdone too; for instance the cybran t3 mobile arty.

**Comment by aeoncleanse** [comment]
Absolutely it's fair. I just have the opinion that we should buff billy to match the visuals rather than the other way around, and even if we choose the latter, I think we need a brand new one. The SCU doesn't scale well, and scaled properly the solution must be.

Also, I agree about the Arty...

**Comment by MrRowey** [comment]
@Garanas is this realy a nessasay change that a acu explosion looks too big ?

**Comment by Garanas** [comment]
I think Keyser took care of this at some point.
