### ISSUE TITLE
t3 mobile arty keeps redeploying while it shouldn't

### ISSUE THREAD

**Issue by RabidPope** [FAForever/fa#5299]
When in range of a target, the unit will fire and then begin to undeploy and redeploy. This gimps the units dps.

**To Reproduce**
Have a trebuchet in range of a target. It only happens if you don't select a target to fire at but let the unit passively choose a target  

**Expected behavior**
It stays deployed to keep firing if targets are in range.

Replay: #20499270

**Comment by RabidPope** [comment]
@Garanas Kind of need help with this one. Where can I start looking? Would like to learn so I can help out more with debugging.

**Comment by Garanas** [comment]
@RabidPope the bug is related to [OnLostTarget](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/defaultweapons.lua#L632-L650) being called prematurely. The target is lost because it is being reset [after firing](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/defaultweapons.lua#L844). 

The question is whether that reset has any value. Considering most units continue scanning targets, it shouldn't. But you'd need to test that, see if the behavior is different.

For your idea, I found out about this by searching for the `WeaponUnpacks` blueprint field in the weapon and default weapon files. Based on that I introduced the following logging to `OnLostTarget`:

```lua
        LOG("OnLostTarget")
        reprsl(debug.traceback())
```

Which tells me that A, the function triggers. And B, where it triggers from. That brought me to that reset target line. This bug likely exists since https://github.com/FAForever/fa/issues/4863

**Comment by RabidPope** [comment]
@Garanas Where/how did you add the logging? Anyway I changed the defaultweapons file to:             
if self.Blueprint.WeaponUnpacks then
               --Do nothing
            else
               self:ResetTarget()
            end
That seems to have fixed it. Checked and other units still change target.

**Comment by RabidPope** [comment]
Question is how the hell do I add a pull request without the other changes? Guess I should have a fork from my own faf dev instead of changing directly on to my own faf dev?

**Comment by Garanas** [comment]
You checkout to the original `deploy/fafdevelop`, in this repository. That will remove all the previous commits. You can add this repository as a remote. You can push your branch to your own remote, create a pull request from there
