### ISSUE TITLE
Show name of player that unpaused

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#542]
Requested [here](http://forums.faforever.com/forums/viewtopic.php?f=2&t=9758) and [here](http://forums.faforever.com/forums/viewtopic.php?f=2&t=7073)

**Comment by Crotalus** [comment]
Yes, I've been looking into this previously, if I remember correctly the data of the player unpausing isn't provided in the unpause() callback. 

We could solve it by manually sending the instigator to the players in the game.

The current UserPlayerQuery() isn't useful because it's sending the messages through the sim layer. We should rather create a new Message system that can be used by UI layer. This is possible with a custom chat channel (I use that kind of system with autoshare and overlay information).

There're other UI-utility functions like getting all your units etc that should be centralised in FAF so all mods can use it, atm alot of code is unnecessary duplicated in seperate mods.

**Comment by Crotalus** [comment]
In the game since 3652
