### ISSUE TITLE
Strategic submarine being able to launch again and again

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#5753]
**Describe the bug**

A strategic submarine that can keep firing strategic missiles. It ends up having a negative missile storage count.

- [Replay (#21426367)](https://replay.faforever.com/21426367)

**To Reproduce**

I have not managed to reproduce it yet. But it has to do with hold fire. It appears to only apply to strategic submarines, but I'm fairly certain that is only because we've not managed to reproduce it properly yet.

**Expected behavior**

To not be able to keep on firing strategic missiles.

**Screenshots**

![image](https://github.com/FAForever/fa/assets/15778155/bc4c7efd-1ff0-475e-8618-af502082a65e)

**Comment by Garanas** [comment]
@lL1l1 as you've been looking into weapons a lot recently, would you be interested in picking up this bug?

**Comment by lL1l1** [comment]
I can replicate it. You basically cache a nuke launch in the 1 second of `PlayFxMuzzleSequence` from the UEF Strategic sub unit script. Other subs don't have this issue because they dont have animations, and static nukes don't hack animations using the unit script.
I'm using the debug logs from my fire cycle fixes, so cherry pick the commit into a test branch. This bug works on the latest fafdevelop version.
I also recommend adding time logs to the unit script's FX waits, setting rack charge time to 0.1, and using 1 buildcost/time missiles with auto-build turned off.
Load nuke -> Hold Fire -> Give Launch Command -> Wait until you finish the rack charge state and enter fire ready state -> Enable fire -> [short time window before the UI missile counter updates: hold fire -> give new launch order] -> nuke launches -> should see idle OnFire trigger -> enable fire -> you will fire another nuke and end up at -1 nukes, thus giving you infinite nukes to fire.
Log you should see when you replicate it
```
INFO: IdleState OnFire 40
INFO: Entered RackSalvoChargeState 40
INFO: Entered FireReadyState70
INFO: entered RackSalvoFiringState98
INFO: PlayFxMuzzleSequence start 108
[I set it to 5 seconds wait time, but it is by default 1 and possible with 1 tick wait]
INFO: PlayFxMuzzleSequence end 158
INFO: Created proj 158
INFO: PlayFxRackReloadSequence start 158
INFO: PlayFxRackReloadSequence end 168
INFO: Entered IdleState 168
[The following OnFire is not supposed to happen, we don't have ammo]
INFO: IdleState OnFire 170
INFO: Entered RackSalvoChargeState 170
INFO: Entered FireReadyState0
[We will fire FOR FREE if you enable fire right now]
```
Without the FX, the UI updates practically instantly so it's impossible to glitch out.
