### ISSUE TITLE
Balance idea: SCU Rebalance

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#6126]
This Issue is just for the Raw SCU stats and Upgrade Changes will Follow

## Base SCU 
- HP Reduction
- Regen Reduction
- Cost balanced 
- Build Power Reduction
- Gun Damage Reduction

## Base Support Ability 
- Aeon: Mini Chrono
- Cybran: Mini Stealth Field
- UEF: Jamming Field
- Sera: Restoration Field

## Gates
- Cost Reduction
- Hp Reduction

Damage & Build Power that has been removed will be added via Upgrades.

**Comment by arch625** [comment]
For posterity's sake I will copy what I wrote in the balance channel here:

I think the most important part towards an SACU rebalance is to have them fulfill some specific niche that they can do better than other alternatives at that tech level (t3 units and experimentals). SACUs should obviously not be viable as combat units over normal t3 or experimental units, so I think the best direction to take them in is to make them support units for your actual army (turin had made some progress here but I don't know where it is). 

Personally I don't think these changes you linked will be that impactful, I don't really use SACUs right now and I probably won't use them after the changes, so to me these changes are just window dressing. 

What I'm envisioning would be to give each faction's SACUs some support ability or that fits the faction. For example, the Sera SACU could have a strong regen field, but since it doesn't stack additively with more SACUs you would just be incentivized to mix them in low numbers in with the rest of your army. The thing is, just a single support ability will be hard to balance, e.g. if we give Cybran could have stealth field, UEF jamming, Aeon Omni vision etc. the combat ability will probably be the most useful. I think maybe then it would be best to give each faction's SACU two support abilities, one combat and one intel support ability, none of which stack additively (with more than 1 SACU in a given radius). I'll list a tentative idea below:

Sera - Regen field, Jamming
Cybran - Regen field, Stealth
UEF - Max HP & Shield HP field, Jamming
Aeon - Max HP & Shield HP field, Stealth

The best way to do it imo would be to just give them this support ability as part of the stock SACU without any upgrades, keep the upgrades as they are, and probably do an overhaul of upgrades at some later date.

**Comment by Garanas** [comment]
The mass income of Seraphim was set to 3 because they have no RAS. It was previously 2. With this pull request it is lowered to 1.

**Comment by MrRowey** [comment]
> The mass income of Seraphim was set to 3 because they have no RAS. It was previously 2. With this pull request it is lowered to 1.

This is still on discussion not finalised
