### ISSUE TITLE
Balance idea: T2 Stationay Arty Nerf

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#6191]
Make it so that they are more inaccurate to prevent them being good at hitting singular targets.

**Comment by Garanas** [comment]
It feels like that we're reaching a point where they become worthless. Specifically their range being nerfed is annoying as the average battleship now out ranges it.

What if instead of making it less accurate, we instead increase the reload costs? The energy costs to reload now is minimal; but we can boost that.
