### ISSUE TITLE
Missing shield effects

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#620]
Removing the `unit:OnShieldEnabled` and `unit:OnShieldDisabled` functions disabled these shield effects in patch 3636.

We need them readded, but instead of using these callbacks so all shields do it, each unit that requires these hooks should indicate this to the shield class on creation somehow.

**Comment by aeoncleanse** [comment]
Which units used these functions? I thought we did a search when we changed this, and found nothing used them?

**Comment by Sheeo** [comment]
Static shields, [original tech support thread here](http://forums.faforever.com/forums/viewtopic.php?f=3&t=9988&sid=284549598beacd4b4dd8296dbbe02870).

**Comment by aeoncleanse** [comment]
Ah got it. Well, you say we don't want all shields to do it, but this applies to all static and all mobile bubbles. So that only leaves out the Continental, the Harbinger, the UEF ACU/SCU, and units with standard personal shields, all of which have their own classes of shield anyway.

He said the rotations were disabled, they are enabled in my tests in release/3641, just the FX missing.
