### ISSUE TITLE
[Feature]: Improving the Novax Satellite and Ground Station giving distinct roles

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#6278]
## Describe the Feature

_This is a Draft all is not final_

This will be a Overhaul on how the Novax works.

# Novax Center Cost

| Unit Stat     | Old Value   | New Value    |
| ------------- | ----------- | ------------ |
| Mass          | 36000       | 29000        |
| Energy        | 512000      | 406000       |
| BuildTime     | 44800       | 36250        |
| Health        | 9000        | 7500         |
| BuildRate     | 300         | 280          |
| WreckageLayer | Water: true | Water: false |

# Novax Center Tech level

| Novax Center Tech Level | Old Value    | New Value |
| ----------------------- | ------------ | --------- |
| Tech Level              | Experimental | Tech 3    |

# Satellites

The Novax will be able to Produce the following satellites. the Station will have a Unit capacity of 3 with each of the satellites using 1- 3 of the slots. the station will no longer have a satellite pre built.

## Scout

| Stat             | Value |
| ---------------- | ----- |
| MassCost         | 5000  |
| EnergyCost       | 75000 |
| EMaintenanceCost | 250   |
| BuildTime        | 15000 |
| VisionRadius     | 75    |
| RadarRadius      | 150   |
| WaterVision      | 50    |
| MaxSpeed         | 10    |
| TurnRate         | 20    |
| Health           | 150   |
| CrashDamage      | 500   |
| UnitSlot         | 1     |

## Support

TBD

## Offensive

| Stat         | Old Value | New Value |
| ------------ | --------- | --------- |
| MassCost     | 10000     | 20000     |
| Energy cost  | 160000    | 250000    |
| BuildTime    | 30000     | 50000     |
| VisionRadius | 60        | 50        |
| RadarRadius  | 200       | 90        |
| MaxSpeed     | 10        | 7         |
| TurnRate     | 20        | 15        |
| Health       | 100       | 50        |
| CrashDamage  | 1000      | 1500      |
| UnitSlot     | -         | 3         |
| **Lazer**    |           |           |
| Damage       | 60        | 75        |
| DamageRadius | 1         | 1.25      |
| Range        | 32        | 28        |
| FireRate     | 20s       | 25s       |
| EFireCost    | 0         | 1000      |

# Counter to satellites

- SMD to be able to manually target a satellite and utilise a smd missile in the process
- alow for a toggle for it to auto fire missile.

**Comment by lolaenter** [comment]
i like this change so much.  I would start playing this game again if this is implemented. for me novax is an extremely strong weapon that lacks counter defense. 

when will it be done?

**Comment by MrRowey** [comment]
> i like this change so much. I would start playing this game again if this is implemented. for me novax is an extremely strong weapon that lacks counter defense.
> 
> when will it be done?

it still in the concept stage and would need to pass bother balance team and game team approval

**Comment by Depony** [comment]
Years ago, I suggested a similar idea, and I recently discussed it with a few people on Discord. Here's what we came up with:

1. **Sat Station Cost and Sat Build Cost:**
   - Sat stations should cost 6,000 mass.
   - Building a standard Sat should cost 16,000 mass and have the same build time as a nuke.
   - Each Sat should have an associated running cost to balance them as a unit. I suggest a running cost of 5,000 energy per tick (for the Sat unit, not the station).

2. **Running Cost and Balance:**
   - Limit each station to support up to 5 Sats.
   - To run a single Sat, it should require the output of 2 T3 power generators.
   - Having 5 Sats per station would thus require 10 T3 power generators, balancing the energy cost for maintaining multiple Sats.

3. **Intel Sats:**
   - Introduce Intel Sats with a suggested cost of 8,000 mass and a 3-minute build time.
   - Intel Sats should have a view radius comparable to an aircraft carrier and should have omni vision with a smaller sonar radius.
   - They should also have a high running cost of 5,000 energy due to their free intel over a large area.

4. **Icons and Adjacency:**
   - Different clear icons should be used for standard Sats and Intel Sats for clarity.
   - Adjacency bonuses for building cheaper Sats over multiple stations should be considered. This could be balanced similarly to the adjacency mechanics of quantum gateways.

5. **Energy Dependency:**
   - To balance their power, Sats should be heavily dependent on energy. A power failure should cause Sats to stop mid-air and trigger a hold fire status, as if they were "dead in the water."


These ideas are intended to slightly nerf Sats by making them more energy-dependent, ensuring that managing them requires careful consideration of energy resources. As the complaints I hear all the time is how Over powered multi Sats are. 

I believe this approach would transform Sats into area denial or counter-navy units rather than base breakers. To balance this, SMDs should be able to manually target and shoot down Sats. 

Imagine having 5 Sats patrolling the mid on Dual Gap or the seas on Setons. Players would be hesitant to commit them to attacking bases due to their high cost and the possibility of being shot down at a lower cost. This vulnerability would be the primary weakness of the suggested changes.

These ideas focus on making Sats less overpowered and more strategically balanced by introducing the risk of being easily countered by SMDs.
 
I believe all the above should be a stepping stone for unit reworks and discussion points to start with.
