### ISSUE TITLE
Engineers repairing a unit continue to drain resources during destruction animation

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#642]
Demonstration in replay 3489971

Factory death animations are only a second or two, but things like shield have 8 second death animations, so lots of resources can be wasted.

**Comment by aeoncleanse** [comment]
Did someone fix this already and not note it? I can't reproduce it :/

**Comment by aeoncleanse** [comment]
Reproduced it now. By telling the assister consumption update to check for focus.Dead and simply set consumption to 0 at that point, I can stop the resource drain, but the engie repair animation continues. Where might we find the "Stop this task engie!" function to turn off consumption and anims in one go, there must BE one because it's called, wherever it is, when the unit finally dies. Basically, we just need to tell repairing units that the unit has died as soon as OnKilled is called.

**Comment by aeoncleanse** [comment]
@Crotalus?

**Comment by quark036** [comment]
In effectutilities.lua, you could try CleanupEffectBag.

**Comment by quark036** [comment]
Further confirmation: units.lua calls CleanupEffectBag from within OnKilled, so it should work.

**Comment by aeoncleanse** [comment]
OK I now have a working fix... However, the Engineer still refuses to rotate the arms back to neutral until the death is fully complete.

**Comment by MrRowey** [comment]
Duplicate issuse
