### ISSUE TITLE
Engine: Enable and redirect bugsplat crash reports

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#703]
After experiencing 5 engine crashes today and through a combination of my own stupidity and then other people crashing and not me not being able to grab the exception and stracktrace, I talked to Sheeo and he suggested we could maybe use the bugsplat integration in FA to report crashes to us.

This requires a couple of steps:
1. Find out how bugsplat builds and submits its reports: This happens in BsSndRpt.exe and the easiest way to figure this out is probably attaching a debugger to it and tracing what happens (IDA should be able to do that?)
2. Implement our own http endpoint that emulates the bugsplat report server well enough that we get the exception info
3. Manipulate the game/bugsplat binaries so they do our bidding and send reports to our server

Some documentation on how bugsplat does things is here: http://www.bugsplatsoftware.com/documents/configuring-visual-c-applications/

**Comment by Sheeo** [comment]
@Eximius this would be right up your alley :)

**Comment by Garanas** [comment]
This issue is becoming more and more relevant as we progress with the FAF project. Being able to **automatically** collect and send all the data when a game crashes (branch, replay id, os, exception code, game log, dump file, exception code) can help us take them down as I feel a lot of people are just thinking: this is a 15 year old game, it crashes every now and then.

@Sheikah45 - up to what degree would this be possible? Two ideas when the game crashes:
 - The client automatically collects all relevant information and makes a new issue on this Github repo with all the data attached.
 - The client automatically collects all relevant information and stores it somehow, allowing us to find it and investigate it.

**Comment by Sheikah45** [comment]
You need an account in order to create a git issue. We may be able to have some webhook on GitHub but it would end up being publicly available which may cause some issues.

Afaik the big splat stuff was taken down and is no longer used. Getting all the info for people to post is definitely doable. Just need to know what all the info is and how to identify it for a particular game

**Comment by Garanas** [comment]
Creating a Github issue may not be the most straightforward approach. 

_Afaik the big splat stuff was taken down and is no longer used_
Are you referring to these files:
![image](https://user-images.githubusercontent.com/15778155/132505044-c7c5ab2d-1a0f-45ba-9cff-1c6d994fcc82.png)
Because these files produce the exception code and the dump file. Do you know where the rationale was to take it down?

**Comment by Sheikah45** [comment]
Oh there was a separate faf bugsplat the client used.

 Those bugsplat files I suspect were pointed at the original GPG bug reporting server so most likely would need some RE if we would want to point them at some other location

**Comment by Garanas** [comment]
@KionX Would that be possible? Because that tool essentially has everything we need (game log file, directx logs, dump file) except for the branch and replay id.

**Comment by KionX** [comment]
Need to change the report sending address? I'll take a look.

**Comment by Garanas** [comment]
Yes - that is I think what we need. Correct me if I'm wrong.

**Comment by KionX** [comment]
HKEY_CURRENT_USER\SOFTWARE\Bugsplat\gaspowered\SupremeCommander\3620\PostDomain

**Comment by Sheikah45** [comment]
Oh nice it is just a registry key. Does it get set only during install or does it get set before each game so you know?

**Comment by Sheikah45** [comment]
@Garanas You can ask Brutus if we ever had an account with bugsplat. Also looks like they may offer some deals for opensource as well.

https://www.bugsplat.com/docs/plans/open-source/

**Comment by Sheikah45** [comment]
Not sure if their format has changed or if our project falls under the definition of open source

**Comment by KionX** [comment]
_Does it get set only during install or does it get set before each game so you know?_
only during install

**Comment by Garanas** [comment]
How hard would it be to make the open source alternative work with the FA executable?

**Comment by KionX** [comment]
Can't know in advance.

**Comment by Sheikah45** [comment]
Yeah would need to know what the format of the report actually is and how that compares to what our endpoint would expect

**Comment by MrRowey** [comment]
@Garanas can this be closed now ?
