### ISSUE TITLE
Cybran builbots invisible to enemies

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#720]
Even once in intel range, the cute little bots are invisible to enemies.

This is kinda a big deal.

https://www.dropbox.com/s/hzvpyf915as8820/Screenshot%202015-07-02%2023.19.54.png?dl=0

**Comment by aeoncleanse** [comment]
Is this old or regression? 0_0

**Comment by ChrisKitching** [comment]
> Is this old or regression? 0_0

Could you find out? I'm juggling other things.

**Comment by aeoncleanse** [comment]
I didn't get time tonight, but a quick glance and I'd bet that this is caused by the unit not having the VISIBLETORECON Category I remember from most units. Optical is recon, so without this...

**Comment by bamboofats** [comment]
This exists since vanilla supcom 1. Some kinda performance saving thing implemented???  The player can only see their own build bots. Allies and enermies are invisible.

The same goes for tyres and wheeled tracked animations. THe units belonging to allies and enermies dont animation. Kinda wierd watching huges experimentals without moving tacks, eg FATboy, scathis. I believe the performance hit now isnt much  that these effects can be safety viewed by all?  

In observer mode for replays, eg 4 players FFA. You can see the effects from all players. When you switch to player A POV, the player B C D build bots invisible/ tracked aminations stop.

**Comment by aeoncleanse** [comment]
Yup, VISIBLETORECON does the trick that I can see. I see them in optics, but no radar sig.
