### ISSUE TITLE
Required mods

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#752]
Mod manager doesn't inform about missing required (UI) mods, it just refuse to turn on the mod if the required mod is missing

**Comment by Crotalus** [comment]
Would also be nice if the client downloaded all required mods at the same time as the main mod

**Comment by ChrisKitching** [comment]
The mod manager is, for the most part, still the train wreck we inherited: bonus points for taking a machette to it.

**Comment by HUSSAR-mtrela** [comment]
It might be difficult to implement because we would need to depend on authors of mods to add names of required mods to the **requiresNames ** table in their mod_info.lua. Usually, they just specify UID in the **requires** table. So should the Mods Manager display a message "Missing mods with uid #####-###-####-####" if a name of required mod is missing? Alternatively, we could get a list of mods names with their UIDs from the mod vault and use it to lookup missing mods. Does anyone know how to get this list?

**Comment by Sheeo** [comment]
@HUSSAR-mtrela there's a json parser and an option to actually get data back into the ingame lobby from the client. It's somewhat experimental (In that I don't believe anyone has actually tested it).

Using this you could use `GpgNetSend` to request names for mods and write a hook for doing something with them when the client responds with resolved names.

Of course; you'll need to poke the python for this.

**Comment by Garanas** [comment]
This is still an issue @Sheikah45 do you reckon it could be fixed as described by Sheeo? Would it be worth it somehow?

As an example: Battle Royale requires the Dear Windowing library, but the latter is a UI mod and therefore it is not auto-downloaded when you join the game.

**Comment by Sheikah45** [comment]
This would still require mod authors to add the required mod uuids to the mod info in a specified format. If they do that consistently then the client could parse them and load them. We wouldn't be able to update after the game is launched though. Additionally there is the question of how to handle a mod  having an older version of another mod as a dependency since currently the client auto updates mods on launch

**Comment by Garanas** [comment]
A proper solution would be a proper version control system, as an example the system that Haskell packages use. But that requires changes all over the board, including this repository, the client and likely the backend too.

I'm going to leave this issue open as it is still relevant.

**Comment by Sheikah45** [comment]
Well even a system like the Haskell just depends on the authors properly recording their version requirements. And with uuids the only issue is that you can only specify a specific mod version. But I don't think that is an issue as I would not assume faf mods to keep dependencies in mind when they make changes so any version change would require changes in the base mod

**Comment by Sheikah45** [comment]
But yeah if the mods put the requires with the comma separated uuids into the mod info then this is just a client side change

**Comment by Garanas** [comment]
Lets leave this open for now and see whether people still need this, as I think there are better places to put our effort into for now.

With regard to my own issue, I am integrating the dear windowing library into the FA repository https://github.com/FAForever/fa/pull/3351 so that the dependency on the UI mod is gone.

**Comment by Garanas** [comment]
Still an issue and it won't likely get fixed any time soon. Bottom line is to not have mods depend on UI mods, as I've experienced with the [Battle Royale](https://github.com/FAForever/Battle-Royale) mod.
