### ISSUE TITLE
Upgraded hives don't take damage from scathis

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#779]
happened in 3655091 , didn't try to sandbox it to confirm , probably faster than watching the replay.

**Comment by Varaxis** [comment]
I encountered an invincible hive in one of my games too. It was upgraded just once. Projectiles went through it. Reclaiming it was the only the only option to get rid of it. 

Confirmed in sandbox, when created by upgraded. Spawned directly, it behaves as normally expected.

**Comment by quark036** [comment]
Hehe I just had a game with this. Turns out it dies to nukes

**Comment by bamboofats** [comment]
I can confirm the stage 2 hive doesnt take damage properly in a sandbox game. Reverting the script files from the 3641 hive bone fix back to the original GPG file appears to solve this. Now that the stage 2 and 3 hives are not directly rebuildable due to the separate SCU rebuilder fix, perhaps a quick way to solve this is to restore those script files for the hives.
