### ISSUE TITLE
Hovering over shielded unit does not show unit detail

### ISSUE THREAD

**Issue by anihilnine** [FAForever/fa#801]
This is the error in the log.

WARNING: Error running OnFrame script in CScriptObject at 1248d480: f:\projects\fa\fa\lua\ui\game\unitview.lua(431): access to nonexistent global variable "ShieldMaxHealth"
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
         	f:\projects\fa\fa\lua\ui\game\unitview.lua(431): in function `UpdateWindow'
         	f:\projects\fa\fa\lua\ui\game\unitview.lua(513): in function <f:\projects\fa\fa\lua\ui\game\unitview.lua:506>

**Comment by duk3luk3** [comment]
Just from code inspection that's a simple typo, it should be ```shieldMaxHealth``` instead of ```ShieldMaxHealth``` (It's on several lines in the unitview.lua). I'll fix it whenever I have time if nobody else does.

How did this slip through though? Are there any lua linters we could use to find issues like that automatically?

**Comment by Sheeo** [comment]
I think it's a rebase of a rebase of a merge, which is why it slipped. I'm held up with the release branch -- I believe @anihilnine is working on fixing this.

**Comment by duk3luk3** [comment]
In that case I believe we should implement a "only fast-forward merges" policy.

It's not hard to rebase onto the branch you want to PR into yourself before submitting the PR. In most cases "git pull --rebase upstream <branchname>" is going to do all the work for you (It stashes all your commits past where your branch and the upstream branch diverge, pulls the upstream branch, and then applies your commits on top of that) - and then you'll see that you messed up (or someone stomped on the same code you were working on and got that into upstream before you did) either by getting merge conflicts or because shit stops working.

**Comment by Sheeo** [comment]
Agreed.

**Comment by anihilnine** [comment]
shieldMaxHealth used with two different cases
shieldRegenRate used with two different cases
shieldText variable not used

`if shieldRegenRate > 0` used inside a `if shieldRegenRate > 0` block

this is a bad merge. roll back
