### ISSUE TITLE
Drones invincible to t1 aa

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#850]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10423

**Comment by bamboofats** [comment]
The t1 aa shoots above them by quite a bit. 
If the drones come real close, the aa can hit and it kills them though.

affects both mobile and static aa. In particular UEF, whose mobile and static aa miss completely.
I could get cybran AAs to hit though.

**Comment by ChrisKitching** [comment]
This is probably resolved with a8e302ddb3393ae248c719912ca7f77ff7806dee

**Comment by ChrisKitching** [comment]
Well, with the reversion of the "remove the AIR category" commit, really.

**Comment by bamboofats** [comment]
@ChrisKitching   I got a strong feel that this issue isnt fixed with the build restrictions. I did quite a bit of tinkering around and found that the drones dont die not because of nodamage  but because of targetting issues which may need some hitbox/targetting bone etc fix.
This issue exists since vanilla FA, but with the recent removal of air-to-drone targetting, the apparent uselessness of the only early counters to drones (t1aa) has become obvious.

If you watch closely, t1aa eg uef, shoots slightly above the centre of airunits. You can see it when shooting stationary gunships. But the shells always collide fine.
For drones, because of the unusually low elevation the aa always misses at the flat firing angle.
You can try increasing the flying elevation of drones, aa will hit them reliably. 
Can also observe that t1aas (eg uef) have some difficulty hitting planes that are close to the ground when landing or taking off, when the firing angle is quite flat.

**Comment by Sheeo** [comment]
@bamboofats that's a bug, which we need a new issue for.

**Comment by ChrisKitching** [comment]
Testing confirms interceptors can destroy drones.
