### ISSUE TITLE
Create some dummy textures or something to get rid of warnings in createunit (cheat) dialog

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#895]
https://gist.github.com/duk3luk3/28f8a16af16a789b2ade

**Comment by ChrisKitching** [comment]
It's in the cheat dialogue, which is only really used for debugging.

Those textures are for campaign units and such that don't have defined icons. Adding icons for them would just be unnecessary bloat. We shouldn't add a check to "UIFile" to handle this case, because that function is _ridiculously_ hot and this would probably have negative perf implications.

One sensible approach might be to simply not load the blueprints for units in the "OPERATION" category.

A nice way to go about that would be to modify the unit restriction system to simply not load blueprints for restricted units. You could then make the restricted unit set always contain the "OPERATION" category, and this problem goes away (by deleting all the problematic units).
This would also slightly improve game load time, which would be nice.

**Comment by duk3luk3** [comment]
Yes, that sounds like a good idea.

**Comment by ChrisKitching** [comment]
If you can do that, you can also remove my extra check from Unit's OnStopBeingBuilt that causes incorrectly created units to explode.

(There is presently nothing stopping UI mods from issuing build orders to make restricted units, so we need to sim-side enforce it somehow. Not loading the blueprint is a nice way of doing it, but I couldn't figure out how quickly enough). This'd be a very welcome change.

**Comment by duk3luk3** [comment]
`LoadBluePrints` in called from `ruleInit.lua` (in mohodata.scd) which is called by the engine it appears.  
Like `simInit.lua` explains in the top comment, blueprints are loaded before ScenarioInfo is processed, which gets us unit restrictions.

I don't see a way to turn this around.

**Comment by ChrisKitching** [comment]
This is exactly the problem I wasn't able to solve quickly enough. With extra magic this can probably be solved (probably by delaying blueprint loading, or retroactively deleting some blueprints)

**Comment by duk3luk3** [comment]
As @speed2CZ notes in referenced issues, this problem also impacts mapmakers. We should probably think about what the easiest achievable not-a-total-hack fix is rather than what the Right[TM] solution is.

Also revisiting @ChrisKitching's comment
> We shouldn't add a check to "UIFile" to handle this case, because that function is ridiculously hot and this would probably have negative perf implications

The following appears to me: You know what has *terrible* perf implications?

```        
WARN(debug.traceback(nil, "Warning: Unable to find file: " .. skins[currentSkin()].texturesPath .. filespec))
```

`debug.traceback` does.

**Comment by ChrisKitching** [comment]
> You know what has terrible perf implications?

We don't care if the debug window is a bit slow.

We do care if _every other UI element in the entire game_ becomes a bit slower in order to make the debug window slightly less slow.

Removing the traceback from this use of UIFile makes it far less useful as a debugging tool.

The best course really seems to be to do nothing.
