### ISSUE TITLE
Mod manager blocking discreprancy between hosting and joining

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#909]
The mod blacklist is interpreted differently depending on whether you host or join a game.

Excerpt from a log from joining:

```
warning: {
warning:     D000E905-1E97-420D-8ED9-DF083282F59D = true
warning:     zcbf6277-24e3-437a-b968-Common-v1 = true
warning: }
info: MOD LIST SET TO:
info:         V2 FA Sequentially upgrading extractors       (D000E905-1E97-420D-8ED9-DF083282F59D)
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
```

When hosting, ecomanager was allowed.

Needs more investigation.

**Comment by HUSSAR-mtrela** [comment]
hmm... we need better logging of warnings in the mod manager. As to this issue, none of these mods are blacklisted so it does not have to do with mod blacklist but rather mod conflicts, dependencies, or mod missing by a player that is joining the game. 

@Sheeo you wrote that ecomanager was allowed when hosting. So the issue here is that it was disabled when joining this game? I asked because uid of ecomanager does not show up in your logs. 
Also, do you have a list of mods that the host of this game had enabled and it would be useful if we had a list of mods of a player that was trying to join. In other words. I would need more info on which mod cause this issue in order for me to try to reproduce it on my end.
