### ISSUE TITLE
Cybran drones cause higher than normal sim speed lag

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#939]
Quick findings from a simple test (ordered to assist a nuker, and watching simspeed in the networkstats window):

100 Cyb SCU drops my simspeed from +10 to +5
100 Hives drops my simspeed from +10 to +5
100 T3 Cyb Eng drops my simspeed from +10 to +7
100 T2 Cyb Eng drops my simspeed from +10 to +8

Any other form of engineers in multiples of 100, my simspeed still +10, including with UEF eng station drones.

Can easily come to the conclusion that the drones themselves are causing simspeed slow down that makes the game unpleasant/frustrating and is unwelcoming to those without decent CPUs.

**Comment by Crotalus** [comment]
Interesting, did some additional testing, it's due to the spark emitters (2 per drone) on the end of the drone's build beam. 

Seems like emitters draw quite a bit of CPU power then, maybe we should put a "throttle" on those by keeping some max number allowed.  Maybe even take into account current sim speed when we decide how many emitters to spawn overall, need to make regular sim speed reports from UI -> sim then.

**Comment by ChrisKitching** [comment]
Is this a property of the base game, as well? If not, maybe it's related to the "drone reuse" changes (though I don't think they cause work most of the time).
Did the "number of drones proportional to build speed" changes lead to a net increase in drone count? (I think it may have done?). Perhaps retune that to get fewer drones?

Instead of reporting simspeed like that, why not just cause some of the emitters to turn off when the fidelity settings are lower?

**Comment by Crotalus** [comment]
Seems like it's only a problem with certain emitters when they are spamming on the same spot, tweaked the cybran sparks some.

Could tune down effects with fidelty I guess, problem is if someone is on high and lagging they will draw down everyone else anyway.
