### ISSUE TITLE
New Upgrade system ignores unit restrictions

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#990]
Noticed in coop that you are allowed to upgate mexes/radars etc even when those units are restricted

**Comment by Crotalus** [comment]
And the unit actually upgrades? If so it the UI is responsible for enforcing restrictions = has to change

**Comment by speed2CZ** [comment]
yes they do upgrade

**Comment by duk3luk3** [comment]
And they don't explode after upgrading?

**Comment by speed2CZ** [comment]
no

**Comment by HUSSAR-mtrela** [comment]
i will try to fix this issue and I think it should be fixed in sim/unit rather than in UI otherwise any UI mod would exploit this issue.

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse @speed2CZ 
so there are  two things that need to be fixed for this issue:
1. ScenarioFramework.AddRestriction() funtion should pass restricted categories to game.lua and update the restrictedCategorySet variable and override UnitRestricted() funtion. 
2. Somewhere in Unit.Lua, we need to check if a unit has restricted upgrade:
- OnStartBeingBuilt
local isRestriced = Game.UnitRestricted(self:GetUnitId(), self)
- or OnStartBuild 
local upgradeID = self:GetBlueprint().General.UpgradesTo
local upgradeBP = __blueprints[upgradeID]
local isRestriced = Game.UnitRestricted(upgradeID, upgradeBP)

not sure how to stop building of the restricted unit such that it does not start again?
self:OnStopBuild() or self:Kill()

So far, I got part number 1 working and I need a bit help with part number 2.

**Comment by aeoncleanse** [comment]
Could simply return end in onstartbuild? If not, self:Destroy().

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ @aeoncleanse 
I got a fix for this issue and I will commit it tomorrow night because I need to cleanup and remove a lot of my debug changes. Should I log a warning message if someone is trying to cheat by building restricted unit? I mean this warning might be useful for someone setting restriction in a scenario and then wondering why units are blowing up when running this scenario.

**Comment by aeoncleanse** [comment]
Go ahead and merge the stuff in the coop mod @speed2CZ . With that, this this then addressed as of @HUSSAR-mtrela 's latest?

**Comment by aeoncleanse** [comment]
a3e78b63929ea98f07f02f8d990adf586dee1a8b tested all working. Changes to maps required, but simple.

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ 
the map scripts will need to be updated such that they add restrictions using this code:
`ScenarioFramework.AddRestriction(player, categories.xal0305) -- Aeon Sniper Bot`
`ScenarioFramework.AddRestriction(player, categories.xaa0202) -- Aeon Swift Wind`
instead of combining all restrictions into one function call:
`ScenarioFramework.AddRestriction(player,`
`            categories.xal0305 + -- Aeon Sniper Bot`
`            categories.xaa0202 + -- Aeon Mid Range fighter (Swift Wind)`
`)`
then you can remove restrictions using this code:
`ScenarioFramework.RemoveRestriction(player, categories.xal0305) -- Aeon Sniper Bot`
`ScenarioFramework.RemoveRestriction(player, categories.xaa0202) -- Aeon Swift Wind`
In order words, categories passed to  AddRestriction() and RemoveRestriction() function must be matching otherwise the game will not remove restrictions.

**Comment by speed2CZ** [comment]
So you're telling me that if I want to restrict everything at the beginning and then slowly unlock it durring the mission I have to write milion lines for every unit and building?

**Comment by aeoncleanse** [comment]
Not at all @speed2CZ . You know where you first restrict everythiing in the map, you use cat + cat + cat... etc? Instead of that, you can put the cat list as a table, and loop over it calling ScenarioFramework.RemoveRestriction(player, v). It's just a slightly different way of doing the same thing. All the normal maps will need updating too, but I'll help with that, it's only a few minutes work for each. 

For the default ones, they already UNrestrict things one unit at a time, using the UIDs, so that's already correct.
